/* Generated by lx */

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>

#include LX_HEADER

static enum lx_sql_token z0(struct lx_sql_lx *lx);
static enum lx_sql_token z1(struct lx_sql_lx *lx);

#if __STDC_VERSION__ >= 199901L
inline
#endif
static int
lx_getc(struct lx_sql_lx *lx)
{
	int c;

	assert(lx != NULL);
	assert(lx->lgetc != NULL);

	if (lx->c != EOF) {
		c = lx->c, lx->c = EOF;
	} else {
		c = lx->lgetc(lx);
		if (c == EOF) {
			return EOF;
		}
	}

	lx->end.byte++;
	lx->end.col++;

	if (c == '\n') {
		lx->end.line++;
		lx->end.col = 1;
	}

	return c;
}

#if __STDC_VERSION__ >= 199901L
inline
#endif
static void
lx_sql_ungetc(struct lx_sql_lx *lx, int c)
{
	assert(lx != NULL);
	assert(lx->c == EOF);

	lx->c = c;

	if (lx->pop != NULL) {
		lx->pop(lx);
	}

	lx->end.byte--;
	lx->end.col--;

	if (c == '\n') {
		lx->end.line--;
		lx->end.col = 0; /* XXX: lost information */
	}
}

int
lx_sql_dynpush(struct lx_sql_lx *lx, char c)
{
	struct lx_dynbuf *t;

	assert(lx != NULL);

	t = lx->buf;

	assert(t != NULL);

	if (t->p == t->a + t->len) {
		size_t len;
		char *tmp;

		if (t->len == 0) {
			assert(LX_DYN_LOW > 0);
			len = LX_DYN_LOW;
		} else {
			len = t->len * LX_DYN_FACTOR;
			if (len < t->len) {
				errno = ERANGE;
				return -1;
			}
		}

		tmp = realloc(t->a, len);
		if (tmp == NULL) {
			return -1;
		}

		t->p   = tmp + (t->p - t->a);
		t->a   = tmp;
		t->len = len;
	}

	assert(t->p != NULL);
	assert(t->a != NULL);

	*t->p++ = c;

	return 0;
}

void
lx_sql_dynpop(struct lx_sql_lx *lx)
{
	struct lx_dynbuf *t;

	assert(lx != NULL);

	t = lx->buf;

	assert(t != NULL);
	assert(t->a != NULL);
	assert(t->p >= t->a);

	if (t->p == t->a) {
		return;
	}

	t->p--;
}

int
lx_sql_dynclear(struct lx_sql_lx *lx)
{
	struct lx_dynbuf *t;

	assert(lx != NULL);

	t = lx->buf;

	assert(t != NULL);

	if (t->len > LX_DYN_HIGH) {
		size_t len;
		char *tmp;

		len = t->len / LX_DYN_FACTOR;

		tmp = realloc(t->a, len);
		if (tmp == NULL) {
			return -1;
		}

		t->a   = tmp;
		t->len = len;
	}

	t->p = t->a;

	return 0;
}

void
lx_sql_dynfree(struct lx_sql_lx *lx)
{
	struct lx_dynbuf *t;

	assert(lx != NULL);

	t = lx->buf;

	assert(t != NULL);

	free(t->a);
}
static enum lx_sql_token
z0(struct lx_sql_lx *lx)
{
	int c;

	enum {
		NONE, S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, 
		S10, S11, S12, S13, S14, S15, S16, S17, S18, S19, 
		S20, S21, S22, S23, S24, S25, S26, S27, S28, S29, 
		S30, S31, S32, S33, S34, S35, S36, S37, S38, S39, 
		S40, S41, S42, S43, S44, S45, S46, S47, S48, S49, 
		S50, S51, S52, S53, S54, S55, S56, S57, S58
	} state;

	assert(lx != NULL);

	if (lx->clear != NULL) {
		lx->clear(lx);
	}

	state = NONE;

	lx->start = lx->end;

	while (c = lx_getc(lx), c != EOF) {
		if (state == NONE) {
			state = S0;
		}

		if (lx->push != NULL) {
			if (-1 == lx->push(lx, c)) {
				return TOK_ERROR;
			}
		}

		switch (state) {
		case S0: /* start */
			switch ((unsigned char) c) {
			case '\x00':
			case '\x01':
			case '\x02':
			case '\x03':
			case '\x04':
			case '\x05':
			case '\x06':
			case '\a':
			case '\b':
			case '\t':
			case '\n':
			case '\v':
			case '\f':
			case '\r':
			case '\x0e':
			case '\x0f':
			case '\x10':
			case '\x11':
			case '\x12':
			case '\x13':
			case '\x14':
			case '\x15':
			case '\x16':
			case '\x17':
			case '\x18':
			case '\x19':
			case '\x1a':
			case '\x1b':
			case '\x1c':
			case '\x1d':
			case '\x1e':
			case '\x1f':
			case ' ':
			case '!':
			case '"':
			case '#':
			case '$':
			case '%':
			case '&':
			case '\'':
			case '(':
			case ')':
			case '*':
			case '+':
			case ',': state = S1; continue;
			case '-': state = S2; continue;
			case '.':
			case '\x2f':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case ':':
			case ';':
			case '<':
			case '=':
			case '>':
			case '?':
			case '@':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z': state = S1; continue;
			case '[': state = S3; continue;
			case '\\': state = S1; continue;
			case ']': state = S4; continue;
			case '^': state = S5; continue;
			case '_':
			case '`':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':
			case '{':
			case '|':
			case '}':
			case '~':
			case '\x7f':
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8a:
			case 0x8b:
			case 0x8c:
			case 0x8d:
			case 0x8e:
			case 0x8f:
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9a:
			case 0x9b:
			case 0x9c:
			case 0x9d:
			case 0x9e:
			case 0x9f:
			case 0xa0:
			case 0xa1:
			case 0xa2:
			case 0xa3:
			case 0xa4:
			case 0xa5:
			case 0xa6:
			case 0xa7:
			case 0xa8:
			case 0xa9:
			case 0xaa:
			case 0xab:
			case 0xac:
			case 0xad:
			case 0xae:
			case 0xaf:
			case 0xb0:
			case 0xb1:
			case 0xb2:
			case 0xb3:
			case 0xb4:
			case 0xb5:
			case 0xb6:
			case 0xb7:
			case 0xb8:
			case 0xb9:
			case 0xba:
			case 0xbb:
			case 0xbc:
			case 0xbd:
			case 0xbe:
			case 0xbf:
			case 0xc0:
			case 0xc1:
			case 0xc2:
			case 0xc3:
			case 0xc4:
			case 0xc5:
			case 0xc6:
			case 0xc7:
			case 0xc8:
			case 0xc9:
			case 0xca:
			case 0xcb:
			case 0xcc:
			case 0xcd:
			case 0xce:
			case 0xcf:
			case 0xd0:
			case 0xd1:
			case 0xd2:
			case 0xd3:
			case 0xd4:
			case 0xd5:
			case 0xd6:
			case 0xd7:
			case 0xd8:
			case 0xd9:
			case 0xda:
			case 0xdb:
			case 0xdc:
			case 0xdd:
			case 0xde:
			case 0xdf:
			case 0xe0:
			case 0xe1:
			case 0xe2:
			case 0xe3:
			case 0xe4:
			case 0xe5:
			case 0xe6:
			case 0xe7:
			case 0xe8:
			case 0xe9:
			case 0xea:
			case 0xeb:
			case 0xec:
			case 0xed:
			case 0xee:
			case 0xef:
			case 0xf0:
			case 0xf1:
			case 0xf2:
			case 0xf3:
			case 0xf4:
			case 0xf5:
			case 0xf6:
			case 0xf7:
			case 0xf8:
			case 0xf9:
			case 0xfa:
			case 0xfb:
			case 0xfc:
			case 0xfd:
			case 0xfe:
			case 0xff: state = S1; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S1: /* e.g. "a" */
			lx_sql_ungetc(lx, c); return TOK_CHAR;

		case S2: /* e.g. "-" */
			lx_sql_ungetc(lx, c); return TOK_RANGE;

		case S3: /* e.g. "[" */
			switch ((unsigned char) c) {
			case ':': state = S6; continue;
			default:  lx_sql_ungetc(lx, c); return TOK_CHAR;
			}

		case S4: /* e.g. "]" */
			lx_sql_ungetc(lx, c); return lx->z = z1, TOK_CLOSEGROUP;

		case S5: /* e.g. "^" */
			lx_sql_ungetc(lx, c); return TOK_INVERT;

		case S6: /* e.g. "[:" */
			switch ((unsigned char) c) {
			case 'A': state = S7; continue;
			case 'D': state = S8; continue;
			case 'L': state = S9; continue;
			case 'S': state = S10; continue;
			case 'U': state = S11; continue;
			case 'W': state = S12; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S7: /* e.g. "[:A" */
			switch ((unsigned char) c) {
			case 'L': state = S48; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S8: /* e.g. "[:D" */
			switch ((unsigned char) c) {
			case 'I': state = S32; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S9: /* e.g. "[:L" */
			switch ((unsigned char) c) {
			case 'O': state = S17; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S10: /* e.g. "[:S" */
			switch ((unsigned char) c) {
			case 'P': state = S23; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S11: /* e.g. "[:U" */
			switch ((unsigned char) c) {
			case 'P': state = S13; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S12: /* e.g. "[:W" */
			switch ((unsigned char) c) {
			case 'H': state = S28; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S13: /* e.g. "[:UP" */
			switch ((unsigned char) c) {
			case 'P': state = S14; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S14: /* e.g. "[:UPP" */
			switch ((unsigned char) c) {
			case 'E': state = S15; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S15: /* e.g. "[:UPPE" */
			switch ((unsigned char) c) {
			case 'R': state = S16; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S16: /* e.g. "[:UPPER" */
			switch ((unsigned char) c) {
			case ':': state = S30; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S17: /* e.g. "[:LO" */
			switch ((unsigned char) c) {
			case 'W': state = S18; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S18: /* e.g. "[:LOW" */
			switch ((unsigned char) c) {
			case 'E': state = S19; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S19: /* e.g. "[:LOWE" */
			switch ((unsigned char) c) {
			case 'R': state = S20; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S20: /* e.g. "[:LOWER" */
			switch ((unsigned char) c) {
			case ':': state = S21; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S21: /* e.g. "[:LOWER:" */
			switch ((unsigned char) c) {
			case ']': state = S22; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S22: /* e.g. "[:LOWER:]" */
			lx_sql_ungetc(lx, c); return TOK_CLASS_LOWER;

		case S23: /* e.g. "[:SP" */
			switch ((unsigned char) c) {
			case 'A': state = S24; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S24: /* e.g. "[:SPA" */
			switch ((unsigned char) c) {
			case 'C': state = S25; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S25: /* e.g. "[:SPAC" */
			switch ((unsigned char) c) {
			case 'E': state = S26; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S26: /* e.g. "[:SPACE" */
			switch ((unsigned char) c) {
			case ':': state = S27; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S27: /* e.g. "[:SPACE:" */
			switch ((unsigned char) c) {
			case ']': state = S47; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S28: /* e.g. "[:WH" */
			switch ((unsigned char) c) {
			case 'I': state = S29; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S29: /* e.g. "[:WHI" */
			switch ((unsigned char) c) {
			case 'T': state = S38; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S30: /* e.g. "[:UPPER:" */
			switch ((unsigned char) c) {
			case ']': state = S31; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S31: /* e.g. "[:UPPER:]" */
			lx_sql_ungetc(lx, c); return TOK_CLASS_UPPER;

		case S32: /* e.g. "[:DI" */
			switch ((unsigned char) c) {
			case 'G': state = S33; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S33: /* e.g. "[:DIG" */
			switch ((unsigned char) c) {
			case 'I': state = S34; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S34: /* e.g. "[:DIGI" */
			switch ((unsigned char) c) {
			case 'T': state = S35; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S35: /* e.g. "[:DIGIT" */
			switch ((unsigned char) c) {
			case ':': state = S36; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S36: /* e.g. "[:DIGIT:" */
			switch ((unsigned char) c) {
			case ']': state = S37; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S37: /* e.g. "[:DIGIT:]" */
			lx_sql_ungetc(lx, c); return TOK_CLASS_DIGIT;

		case S38: /* e.g. "[:WHIT" */
			switch ((unsigned char) c) {
			case 'E': state = S39; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S39: /* e.g. "[:WHITE" */
			switch ((unsigned char) c) {
			case 'S': state = S40; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S40: /* e.g. "[:WHITES" */
			switch ((unsigned char) c) {
			case 'P': state = S41; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S41: /* e.g. "[:WHITESP" */
			switch ((unsigned char) c) {
			case 'A': state = S42; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S42: /* e.g. "[:WHITESPA" */
			switch ((unsigned char) c) {
			case 'C': state = S43; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S43: /* e.g. "[:WHITESPAC" */
			switch ((unsigned char) c) {
			case 'E': state = S44; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S44: /* e.g. "[:WHITESPACE" */
			switch ((unsigned char) c) {
			case ':': state = S45; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S45: /* e.g. "[:WHITESPACE:" */
			switch ((unsigned char) c) {
			case ']': state = S46; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S46: /* e.g. "[:WHITESPACE:]" */
			lx_sql_ungetc(lx, c); return TOK_CLASS_SPACE;

		case S47: /* e.g. "[:SPACE:]" */
			lx_sql_ungetc(lx, c); return TOK_CLASS_SPCHR;

		case S48: /* e.g. "[:AL" */
			switch ((unsigned char) c) {
			case 'N': state = S49; continue;
			case 'P': state = S50; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S49: /* e.g. "[:ALN" */
			switch ((unsigned char) c) {
			case 'U': state = S51; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S50: /* e.g. "[:ALP" */
			switch ((unsigned char) c) {
			case 'H': state = S55; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S51: /* e.g. "[:ALNU" */
			switch ((unsigned char) c) {
			case 'M': state = S52; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S52: /* e.g. "[:ALNUM" */
			switch ((unsigned char) c) {
			case ':': state = S53; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S53: /* e.g. "[:ALNUM:" */
			switch ((unsigned char) c) {
			case ']': state = S54; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S54: /* e.g. "[:ALNUM:]" */
			lx_sql_ungetc(lx, c); return TOK_CLASS_ALNUM;

		case S55: /* e.g. "[:ALPH" */
			switch ((unsigned char) c) {
			case 'A': state = S56; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S56: /* e.g. "[:ALPHA" */
			switch ((unsigned char) c) {
			case ':': state = S57; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S57: /* e.g. "[:ALPHA:" */
			switch ((unsigned char) c) {
			case ']': state = S58; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S58: /* e.g. "[:ALPHA:]" */
			lx_sql_ungetc(lx, c); return TOK_CLASS_ALPHA;
		}
	}

	lx->lgetc = NULL;

	switch (state) {
	case NONE: return TOK_EOF;
	case S1: return TOK_CHAR;
	case S2: return TOK_RANGE;
	case S3: return TOK_CHAR;
	case S4: return TOK_CLOSEGROUP;
	case S5: return TOK_INVERT;
	case S22: return TOK_CLASS_LOWER;
	case S31: return TOK_CLASS_UPPER;
	case S37: return TOK_CLASS_DIGIT;
	case S46: return TOK_CLASS_SPACE;
	case S47: return TOK_CLASS_SPCHR;
	case S54: return TOK_CLASS_ALNUM;
	case S58: return TOK_CLASS_ALPHA;
	default: errno = EINVAL; return TOK_ERROR;
	}
}

static enum lx_sql_token
z1(struct lx_sql_lx *lx)
{
	int c;

	enum {
		NONE, S0, S1, S2, S3, S4, S5, S6, S7, S8, S9, 
		S10
	} state;

	assert(lx != NULL);

	if (lx->clear != NULL) {
		lx->clear(lx);
	}

	state = NONE;

	lx->start = lx->end;

	while (c = lx_getc(lx), c != EOF) {
		if (state == NONE) {
			state = S0;
		}

		if (lx->push != NULL) {
			if (-1 == lx->push(lx, c)) {
				return TOK_ERROR;
			}
		}

		switch (state) {
		case S0: /* start */
			switch ((unsigned char) c) {
			case '\x00':
			case '\x01':
			case '\x02':
			case '\x03':
			case '\x04':
			case '\x05':
			case '\x06':
			case '\a':
			case '\b':
			case '\t':
			case '\n':
			case '\v':
			case '\f':
			case '\r':
			case '\x0e':
			case '\x0f':
			case '\x10':
			case '\x11':
			case '\x12':
			case '\x13':
			case '\x14':
			case '\x15':
			case '\x16':
			case '\x17':
			case '\x18':
			case '\x19':
			case '\x1a':
			case '\x1b':
			case '\x1c':
			case '\x1d':
			case '\x1e':
			case '\x1f':
			case ' ':
			case '!':
			case '"':
			case '#':
			case '$': state = S1; continue;
			case '%': state = S2; continue;
			case '&':
			case '\'': state = S1; continue;
			case '(': state = S3; continue;
			case ')': state = S4; continue;
			case '*': state = S5; continue;
			case '+': state = S6; continue;
			case ',':
			case '-':
			case '.':
			case '\x2f':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case ':':
			case ';':
			case '<':
			case '=':
			case '>': state = S1; continue;
			case '?': state = S7; continue;
			case '@':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z': state = S1; continue;
			case '[': state = S8; continue;
			case '\\':
			case ']':
			case '^': state = S1; continue;
			case '_': state = S9; continue;
			case '`':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':
			case '{': state = S1; continue;
			case '|': state = S10; continue;
			case '}':
			case '~':
			case '\x7f':
			case 0x80:
			case 0x81:
			case 0x82:
			case 0x83:
			case 0x84:
			case 0x85:
			case 0x86:
			case 0x87:
			case 0x88:
			case 0x89:
			case 0x8a:
			case 0x8b:
			case 0x8c:
			case 0x8d:
			case 0x8e:
			case 0x8f:
			case 0x90:
			case 0x91:
			case 0x92:
			case 0x93:
			case 0x94:
			case 0x95:
			case 0x96:
			case 0x97:
			case 0x98:
			case 0x99:
			case 0x9a:
			case 0x9b:
			case 0x9c:
			case 0x9d:
			case 0x9e:
			case 0x9f:
			case 0xa0:
			case 0xa1:
			case 0xa2:
			case 0xa3:
			case 0xa4:
			case 0xa5:
			case 0xa6:
			case 0xa7:
			case 0xa8:
			case 0xa9:
			case 0xaa:
			case 0xab:
			case 0xac:
			case 0xad:
			case 0xae:
			case 0xaf:
			case 0xb0:
			case 0xb1:
			case 0xb2:
			case 0xb3:
			case 0xb4:
			case 0xb5:
			case 0xb6:
			case 0xb7:
			case 0xb8:
			case 0xb9:
			case 0xba:
			case 0xbb:
			case 0xbc:
			case 0xbd:
			case 0xbe:
			case 0xbf:
			case 0xc0:
			case 0xc1:
			case 0xc2:
			case 0xc3:
			case 0xc4:
			case 0xc5:
			case 0xc6:
			case 0xc7:
			case 0xc8:
			case 0xc9:
			case 0xca:
			case 0xcb:
			case 0xcc:
			case 0xcd:
			case 0xce:
			case 0xcf:
			case 0xd0:
			case 0xd1:
			case 0xd2:
			case 0xd3:
			case 0xd4:
			case 0xd5:
			case 0xd6:
			case 0xd7:
			case 0xd8:
			case 0xd9:
			case 0xda:
			case 0xdb:
			case 0xdc:
			case 0xdd:
			case 0xde:
			case 0xdf:
			case 0xe0:
			case 0xe1:
			case 0xe2:
			case 0xe3:
			case 0xe4:
			case 0xe5:
			case 0xe6:
			case 0xe7:
			case 0xe8:
			case 0xe9:
			case 0xea:
			case 0xeb:
			case 0xec:
			case 0xed:
			case 0xee:
			case 0xef:
			case 0xf0:
			case 0xf1:
			case 0xf2:
			case 0xf3:
			case 0xf4:
			case 0xf5:
			case 0xf6:
			case 0xf7:
			case 0xf8:
			case 0xf9:
			case 0xfa:
			case 0xfb:
			case 0xfc:
			case 0xfd:
			case 0xfe:
			case 0xff: state = S1; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S1: /* e.g. "a" */
			lx_sql_ungetc(lx, c); return TOK_CHAR;

		case S2: /* e.g. "%" */
			lx_sql_ungetc(lx, c); return TOK_MANY;

		case S3: /* e.g. "(" */
			lx_sql_ungetc(lx, c); return TOK_OPENSUB;

		case S4: /* e.g. ")" */
			lx_sql_ungetc(lx, c); return TOK_CLOSESUB;

		case S5: /* e.g. "*" */
			lx_sql_ungetc(lx, c); return TOK_STAR;

		case S6: /* e.g. "+" */
			lx_sql_ungetc(lx, c); return TOK_PLUS;

		case S7: /* e.g. "?" */
			lx_sql_ungetc(lx, c); return TOK_OPT;

		case S8: /* e.g. "[" */
			lx_sql_ungetc(lx, c); return lx->z = z0, TOK_OPENGROUP;

		case S9: /* e.g. "_" */
			lx_sql_ungetc(lx, c); return TOK_ANY;

		case S10: /* e.g. "|" */
			lx_sql_ungetc(lx, c); return TOK_ALT;
		}
	}

	lx->lgetc = NULL;

	switch (state) {
	case NONE: return TOK_EOF;
	case S1: return TOK_CHAR;
	case S2: return TOK_MANY;
	case S3: return TOK_OPENSUB;
	case S4: return TOK_CLOSESUB;
	case S5: return TOK_STAR;
	case S6: return TOK_PLUS;
	case S7: return TOK_OPT;
	case S8: return TOK_OPENGROUP;
	case S9: return TOK_ANY;
	case S10: return TOK_ALT;
	default: errno = EINVAL; return TOK_ERROR;
	}
}

const char *
lx_sql_name(enum lx_sql_token t)
{
	switch (t) {
	case TOK_CHAR: return "CHAR";
	case TOK_CLASS_SPACE: return "CLASS_SPACE";
	case TOK_CLASS_UPPER: return "CLASS_UPPER";
	case TOK_CLASS_SPCHR: return "CLASS_SPCHR";
	case TOK_CLASS_LOWER: return "CLASS_LOWER";
	case TOK_CLASS_DIGIT: return "CLASS_DIGIT";
	case TOK_CLASS_ALPHA: return "CLASS_ALPHA";
	case TOK_CLASS_ALNUM: return "CLASS_ALNUM";
	case TOK_RANGE: return "RANGE";
	case TOK_INVERT: return "INVERT";
	case TOK_CLOSEGROUP: return "CLOSEGROUP";
	case TOK_OPENGROUP: return "OPENGROUP";
	case TOK_ALT: return "ALT";
	case TOK_PLUS: return "PLUS";
	case TOK_STAR: return "STAR";
	case TOK_OPT: return "OPT";
	case TOK_CLOSESUB: return "CLOSESUB";
	case TOK_OPENSUB: return "OPENSUB";
	case TOK_MANY: return "MANY";
	case TOK_ANY: return "ANY";
	case TOK_EOF:     return "EOF";
	case TOK_ERROR:   return "ERROR";
	case TOK_UNKNOWN: return "UNKNOWN";
	default: return "?";
	}
}

const char *
lx_sql_example(enum lx_sql_token (*z)(struct lx_sql_lx *), enum lx_sql_token t)
{
	assert(z != NULL);

	if (z == z0) {
		switch (t) {
		case TOK_CHAR: return "a";
		case TOK_CLASS_SPACE: return "[:WHITESPACE:]";
		case TOK_CLASS_UPPER: return "[:UPPER:]";
		case TOK_CLASS_SPCHR: return "[:SPACE:]";
		case TOK_CLASS_LOWER: return "[:LOWER:]";
		case TOK_CLASS_DIGIT: return "[:DIGIT:]";
		case TOK_CLASS_ALPHA: return "[:ALPHA:]";
		case TOK_CLASS_ALNUM: return "[:ALNUM:]";
		case TOK_RANGE: return "-";
		case TOK_INVERT: return "^";
		case TOK_CLOSEGROUP: return "]";
		default: goto error;
		}
	} else
	if (z == z1) {
		switch (t) {
		case TOK_CHAR: return "a";
		case TOK_OPENGROUP: return "[";
		case TOK_ALT: return "|";
		case TOK_PLUS: return "+";
		case TOK_STAR: return "*";
		case TOK_OPT: return "?";
		case TOK_CLOSESUB: return ")";
		case TOK_OPENSUB: return "(";
		case TOK_MANY: return "%";
		case TOK_ANY: return "_";
		default: goto error;
		}
	}

error:

	errno = EINVAL;
	return NULL;
}

void
lx_sql_init(struct lx_sql_lx *lx)
{
	static const struct lx_sql_lx lx_default;

	assert(lx != NULL);

	*lx = lx_default;

	lx->c = EOF;
	lx->z = z1;

	lx->end.byte = 0;
	lx->end.line = 1;
	lx->end.col  = 1;
}

enum lx_sql_token
lx_sql_next(struct lx_sql_lx *lx)
{
	enum lx_sql_token t;

	assert(lx != NULL);
	assert(lx->z != NULL);

	if (lx->lgetc == NULL) {
		return TOK_EOF;
	}

	t = lx->z(lx);

	if (lx->push != NULL) {
		if (-1 == lx->push(lx, '\0')) {
			return TOK_ERROR;
		}
	}

	return t;
}

