# $Id$

.include "Makefile.inc"


CFLAGS+= -I ${BASE_DIR}/src
CFLAGS+= -I ${BASE_DIR}/include

# predicates
SRCS+= isany.c
SRCS+= isdfa.c
SRCS+= isend.c
SRCS+= iscomplete.c
SRCS+= hasincoming.c
SRCS+= hasoutgoing.c

.include <lx.obj.mk>

.include <lx.partial.mk>

