.include "../../share/mk/top.mk"

STAGE_COPY += include/fsm/bool.h
STAGE_COPY += include/fsm/cost.h
STAGE_COPY += include/fsm/exec.h
STAGE_COPY += include/fsm/fsm.h
STAGE_COPY += include/fsm/graph.h
STAGE_COPY += include/fsm/out.h
STAGE_COPY += include/fsm/pred.h
STAGE_COPY += include/fsm/search.h
STAGE_COPY += include/fsm/walk.h

