.include "../../share/mk/top.mk"

STAGE_COPY += include/fsm/alloc.h
STAGE_COPY += include/fsm/bool.h
STAGE_COPY += include/fsm/capture.h
STAGE_COPY += include/fsm/cost.h
STAGE_COPY += include/fsm/fsm.h
STAGE_COPY += include/fsm/options.h
STAGE_COPY += include/fsm/pred.h
STAGE_COPY += include/fsm/print.h
STAGE_COPY += include/fsm/walk.h

