#!/bin/sh

BUILD=../build
FUZZER=${BUILD}/fuzz/fuzzer
SEEDS=${BUILD}/fuzz/fuzzer_seeds

ARG=$1

SECONDS=${SECONDS:-60}
WORKERS=${WORKERS:-4}
SEEDS=${SEEDS:-seeds}

if [ "${1}" = "-h" ]; then
    echo "usage: $0"
    echo " - set these via env: [WORKERS=${WORKERS}] [SECONDS=${SECONDS}] [SEEDS=seed_directory]"
    exit 0
fi

if [ ! -e "${FUZZER}" ]; then
    echo "Fuzzer ${FUZZER} does not exist, build 'fuzzer' first."
    exit 1
fi

UBSAN_OPTIONS="ASAN_OPTIONS=detect_leaks=0:halt_on_error=1 UBSAN_OPTIONS=print_stacktrace=1:halt_on_error=1"

if [ ! -d "${SEEDS}" ]; then
   mkdir -p "${SEEDS}"
fi

if [ -z "${ARG}" ]; then
    echo "\n==== ${FUZZER}"
    exec ${FUZZER} -jobs=${WORKERS} -workers=${WORKERS} -max_total_time=${SECONDS} ${SEEDS}
else
    exec ${FUZZER} ${ARG}
fi