/* generated */

#include <assert.h>
#include <string.h>
#include <stddef.h>

#include "class.h"

static struct {
	class_constructor *ctor;
	const char *name;
} classes[] = {
	{ class_alnum_fsm, "alnum" },
	{ class_alpha_fsm, "alpha" },
	{ class_any_fsm, "any" },
	{ class_ascii_fsm, "ascii" },
	{ class_cntrl_fsm, "cntrl" },
	{ class_digit_fsm, "digit" },
	{ class_graph_fsm, "graph" },
	{ class_hspace_fsm, "hspace" },
	{ class_lower_fsm, "lower" },
	{ class_print_fsm, "print" },
	{ class_punct_fsm, "punct" },
	{ class_space_fsm, "space" },
	{ class_spchr_fsm, "spchr" },
	{ class_upper_fsm, "upper" },
	{ class_vspace_fsm, "vspace" },
	{ class_word_fsm, "word" },
	{ class_xdigit_fsm, "xdigit" },
	{ class_notdigit_fsm, "notdigit" },
	{ class_nothspace_fsm, "nothspace" },
	{ class_notspace_fsm, "notspace" },
	{ class_notvspace_fsm, "notvspace" },
	{ class_notword_fsm, "notword" },
	{ class_notnl_fsm, "notnl" },

	{ utf8_Adlam_fsm, "Adlam" },
	{ utf8_Ahom_fsm, "Ahom" },
	{ utf8_Anatolian_Hieroglyphs_fsm, "Anatolian Hieroglyphs" },
	{ utf8_Arabic_fsm, "Arabic" },
	{ utf8_Armenian_fsm, "Armenian" },
	{ utf8_Avestan_fsm, "Avestan" },
	{ utf8_Balinese_fsm, "Balinese" },
	{ utf8_Bamum_fsm, "Bamum" },
	{ utf8_Bassa_Vah_fsm, "Bassa Vah" },
	{ utf8_Batak_fsm, "Batak" },
	{ utf8_Bengali_fsm, "Bengali" },
	{ utf8_Bhaiksuki_fsm, "Bhaiksuki" },
	{ utf8_Bopomofo_fsm, "Bopomofo" },
	{ utf8_Brahmi_fsm, "Brahmi" },
	{ utf8_Braille_fsm, "Braille" },
	{ utf8_Buginese_fsm, "Buginese" },
	{ utf8_Buhid_fsm, "Buhid" },
	{ utf8_Canadian_Aboriginal_fsm, "Canadian Aboriginal" },
	{ utf8_Carian_fsm, "Carian" },
	{ utf8_Caucasian_Albanian_fsm, "Caucasian Albanian" },
	{ utf8_Chakma_fsm, "Chakma" },
	{ utf8_Cham_fsm, "Cham" },
	{ utf8_Cherokee_fsm, "Cherokee" },
	{ utf8_Common_fsm, "Common" },
	{ utf8_Coptic_fsm, "Coptic" },
	{ utf8_Cuneiform_fsm, "Cuneiform" },
	{ utf8_Cypriot_fsm, "Cypriot" },
	{ utf8_Cyrillic_fsm, "Cyrillic" },
	{ utf8_Deseret_fsm, "Deseret" },
	{ utf8_Devanagari_fsm, "Devanagari" },
	{ utf8_Duployan_fsm, "Duployan" },
	{ utf8_Egyptian_Hieroglyphs_fsm, "Egyptian Hieroglyphs" },
	{ utf8_Elbasan_fsm, "Elbasan" },
	{ utf8_Ethiopic_fsm, "Ethiopic" },
	{ utf8_Georgian_fsm, "Georgian" },
	{ utf8_Glagolitic_fsm, "Glagolitic" },
	{ utf8_Gothic_fsm, "Gothic" },
	{ utf8_Grantha_fsm, "Grantha" },
	{ utf8_Greek_fsm, "Greek" },
	{ utf8_Gujarati_fsm, "Gujarati" },
	{ utf8_Gurmukhi_fsm, "Gurmukhi" },
	{ utf8_Han_fsm, "Han" },
	{ utf8_Hangul_fsm, "Hangul" },
	{ utf8_Hanunoo_fsm, "Hanunoo" },
	{ utf8_Hatran_fsm, "Hatran" },
	{ utf8_Hebrew_fsm, "Hebrew" },
	{ utf8_Hiragana_fsm, "Hiragana" },
	{ utf8_Imperial_Aramaic_fsm, "Imperial Aramaic" },
	{ utf8_Inherited_fsm, "Inherited" },
	{ utf8_Inscriptional_Pahlavi_fsm, "Inscriptional Pahlavi" },
	{ utf8_Inscriptional_Parthian_fsm, "Inscriptional Parthian" },
	{ utf8_Javanese_fsm, "Javanese" },
	{ utf8_Kaithi_fsm, "Kaithi" },
	{ utf8_Kannada_fsm, "Kannada" },
	{ utf8_Katakana_fsm, "Katakana" },
	{ utf8_Kayah_Li_fsm, "Kayah Li" },
	{ utf8_Kharoshthi_fsm, "Kharoshthi" },
	{ utf8_Khmer_fsm, "Khmer" },
	{ utf8_Khojki_fsm, "Khojki" },
	{ utf8_Khudawadi_fsm, "Khudawadi" },
	{ utf8_Lao_fsm, "Lao" },
	{ utf8_Latin_fsm, "Latin" },
	{ utf8_Lepcha_fsm, "Lepcha" },
	{ utf8_Limbu_fsm, "Limbu" },
	{ utf8_Linear_A_fsm, "Linear A" },
	{ utf8_Linear_B_fsm, "Linear B" },
	{ utf8_Lisu_fsm, "Lisu" },
	{ utf8_Lycian_fsm, "Lycian" },
	{ utf8_Lydian_fsm, "Lydian" },
	{ utf8_Mahajani_fsm, "Mahajani" },
	{ utf8_Malayalam_fsm, "Malayalam" },
	{ utf8_Mandaic_fsm, "Mandaic" },
	{ utf8_Manichaean_fsm, "Manichaean" },
	{ utf8_Marchen_fsm, "Marchen" },
	{ utf8_Masaram_Gondi_fsm, "Masaram Gondi" },
	{ utf8_Meetei_Mayek_fsm, "Meetei Mayek" },
	{ utf8_Mende_Kikakui_fsm, "Mende Kikakui" },
	{ utf8_Meroitic_Cursive_fsm, "Meroitic Cursive" },
	{ utf8_Meroitic_Hieroglyphs_fsm, "Meroitic Hieroglyphs" },
	{ utf8_Miao_fsm, "Miao" },
	{ utf8_Modi_fsm, "Modi" },
	{ utf8_Mongolian_fsm, "Mongolian" },
	{ utf8_Mro_fsm, "Mro" },
	{ utf8_Multani_fsm, "Multani" },
	{ utf8_Myanmar_fsm, "Myanmar" },
	{ utf8_Nabataean_fsm, "Nabataean" },
	{ utf8_New_Tai_Lue_fsm, "New Tai Lue" },
	{ utf8_Newa_fsm, "Newa" },
	{ utf8_Nko_fsm, "Nko" },
	{ utf8_Nushu_fsm, "Nushu" },
	{ utf8_Ogham_fsm, "Ogham" },
	{ utf8_Ol_Chiki_fsm, "Ol Chiki" },
	{ utf8_Old_Hungarian_fsm, "Old Hungarian" },
	{ utf8_Old_Italic_fsm, "Old Italic" },
	{ utf8_Old_North_Arabian_fsm, "Old North Arabian" },
	{ utf8_Old_Permic_fsm, "Old Permic" },
	{ utf8_Old_Persian_fsm, "Old Persian" },
	{ utf8_Old_South_Arabian_fsm, "Old South Arabian" },
	{ utf8_Old_Turkic_fsm, "Old Turkic" },
	{ utf8_Oriya_fsm, "Oriya" },
	{ utf8_Osage_fsm, "Osage" },
	{ utf8_Osmanya_fsm, "Osmanya" },
	{ utf8_Pahawh_Hmong_fsm, "Pahawh Hmong" },
	{ utf8_Palmyrene_fsm, "Palmyrene" },
	{ utf8_Pau_Cin_Hau_fsm, "Pau Cin Hau" },
	{ utf8_Phags_Pa_fsm, "Phags Pa" },
	{ utf8_Phoenician_fsm, "Phoenician" },
	{ utf8_Psalter_Pahlavi_fsm, "Psalter Pahlavi" },
	{ utf8_Rejang_fsm, "Rejang" },
	{ utf8_Runic_fsm, "Runic" },
	{ utf8_Samaritan_fsm, "Samaritan" },
	{ utf8_Saurashtra_fsm, "Saurashtra" },
	{ utf8_Sharada_fsm, "Sharada" },
	{ utf8_Shavian_fsm, "Shavian" },
	{ utf8_Siddham_fsm, "Siddham" },
	{ utf8_SignWriting_fsm, "SignWriting" },
	{ utf8_Sinhala_fsm, "Sinhala" },
	{ utf8_Sora_Sompeng_fsm, "Sora Sompeng" },
	{ utf8_Soyombo_fsm, "Soyombo" },
	{ utf8_Sundanese_fsm, "Sundanese" },
	{ utf8_Syloti_Nagri_fsm, "Syloti Nagri" },
	{ utf8_Syriac_fsm, "Syriac" },
	{ utf8_Tagalog_fsm, "Tagalog" },
	{ utf8_Tagbanwa_fsm, "Tagbanwa" },
	{ utf8_Tai_Le_fsm, "Tai Le" },
	{ utf8_Tai_Tham_fsm, "Tai Tham" },
	{ utf8_Tai_Viet_fsm, "Tai Viet" },
	{ utf8_Takri_fsm, "Takri" },
	{ utf8_Tamil_fsm, "Tamil" },
	{ utf8_Tangut_fsm, "Tangut" },
	{ utf8_Telugu_fsm, "Telugu" },
	{ utf8_Thaana_fsm, "Thaana" },
	{ utf8_Thai_fsm, "Thai" },
	{ utf8_Tibetan_fsm, "Tibetan" },
	{ utf8_Tifinagh_fsm, "Tifinagh" },
	{ utf8_Tirhuta_fsm, "Tirhuta" },
	{ utf8_Ugaritic_fsm, "Ugaritic" },
	{ utf8_Vai_fsm, "Vai" },
	{ utf8_Warang_Citi_fsm, "Warang Citi" },
	{ utf8_Yi_fsm, "Yi" },
	{ utf8_Zanabazar_Square_fsm, "Zanabazar Square" },
	{ utf8_C_fsm, "C" },
	{ utf8_L_fsm, "L" },
	{ utf8_M_fsm, "M" },
	{ utf8_N_fsm, "N" },
	{ utf8_P_fsm, "P" },
	{ utf8_S_fsm, "S" },
	{ utf8_Z_fsm, "Z" },
	{ utf8_Cf_fsm, "Cf" },
	{ utf8_Co_fsm, "Co" },
	{ utf8_Cs_fsm, "Cs" },
	{ utf8_Ll_fsm, "Ll" },
	{ utf8_Lm_fsm, "Lm" },
	{ utf8_Lo_fsm, "Lo" },
	{ utf8_Lt_fsm, "Lt" },
	{ utf8_Lu_fsm, "Lu" },
	{ utf8_Mc_fsm, "Mc" },
	{ utf8_Me_fsm, "Me" },
	{ utf8_Mn_fsm, "Mn" },
	{ utf8_Nd_fsm, "Nd" },
	{ utf8_Nl_fsm, "Nl" },
	{ utf8_No_fsm, "No" },
	{ utf8_Pc_fsm, "Pc" },
	{ utf8_Pd_fsm, "Pd" },
	{ utf8_Pe_fsm, "Pe" },
	{ utf8_Pf_fsm, "Pf" },
	{ utf8_Pi_fsm, "Pi" },
	{ utf8_Po_fsm, "Po" },
	{ utf8_Ps_fsm, "Ps" },
	{ utf8_Sc_fsm, "Sc" },
	{ utf8_Sk_fsm, "Sk" },
	{ utf8_Sm_fsm, "Sm" },
	{ utf8_So_fsm, "So" },
	{ utf8_Zl_fsm, "Zl" },
	{ utf8_Zp_fsm, "Zp" },
	{ utf8_Zs_fsm, "Zs" },
	{ utf8_private_fsm, "private" },
	{ utf8_assigned_fsm, "assigned" },
	{ utf8_all_fsm, "all" },

	{ NULL, NULL }
};

const char *
class_name(class_constructor *ctor)
{
	size_t i;

	assert(ctor != NULL);

	for (i = 0; i < sizeof classes / sizeof *classes; i++) {
		if (ctor == classes[i].ctor) {
			return classes[i].name;
		}
	}

	return NULL;
}

