/* Generated by lx */

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>

#include <unistd.h>
#include <fcntl.h>

#include LX_HEADER

static enum lx_simple_token z1(struct lx_simple_lx *lx);
static enum lx_simple_token z2(struct lx_simple_lx *lx);
static enum lx_simple_token z3(struct lx_simple_lx *lx);

static int
lx_getc(struct lx_simple_lx *lx)
{
	int c;

	assert(lx != NULL);
	assert(lx->lgetc != NULL);

	if (lx->c != EOF) {
		c = lx->c, lx->c = EOF;
	} else {
		c = lx->lgetc(lx);
		if (c == EOF) {
			return EOF;
		}
	}

	lx->end.byte++;
	lx->end.col++;

	if (c == '\n') {
		lx->end.line++;
		lx->end.col = 1;
	}

	return c;
}

static void
lx_simple_ungetc(struct lx_simple_lx *lx, int c)
{
	assert(lx != NULL);
	assert(lx->c == EOF);

	lx->c = c;

	if (lx->pop != NULL) {
		lx->pop(lx);
	}

	lx->end.byte--;
	lx->end.col--;

	if (c == '\n') {
		lx->end.line--;
		lx->end.col = 0; /* XXX: lost information */
	}
}

int
lx_simple_fgetc(struct lx_simple_lx *lx)
{
	assert(lx != NULL);
	assert(lx->opaque != NULL);

	return fgetc(lx->opaque);
}

int
lx_simple_sgetc(struct lx_simple_lx *lx)
{
	char *s;

	assert(lx != NULL);
	assert(lx->opaque != NULL);

	s = lx->opaque;
	if (*s == '\0') {
		return EOF;
	}

	return lx->opaque = s + 1, *s;
}

int
lx_simple_agetc(struct lx_simple_lx *lx)
{
	struct lx_arr *a;

	assert(lx != NULL);
	assert(lx->opaque != NULL);

	a = lx->opaque;

	assert(a != NULL);
	assert(a->p != NULL);

	if (a->len == 0) {
		return EOF;
	}

	return a->len--, *a->p++;
}

int
lx_simple_dgetc(struct lx_simple_lx *lx)
{
	struct lx_fd *d;

	assert(lx != NULL);
	assert(lx->opaque != NULL);

	d = lx->opaque;
	assert(d->fd != -1);
	assert(d->p != NULL);

	if (d->len == 0) {
		ssize_t r;

		assert((fcntl(d->fd, F_GETFL) & O_NONBLOCK) == 0);

		d->p = (char *) d + sizeof *d;

		r = read(d->fd, d->p, d->bufsz);
		if (r == -1) {
			assert(errno != EAGAIN);
			return EOF;
		}

		if (r == 0) {
			return EOF;
		}

		d->len = r;
	}

	return d->len--, *d->p++;
}

int
lx_simple_dynpush(struct lx_simple_lx *lx, char c)
{
	struct lx_dynbuf *t;

	assert(lx != NULL);
	assert(c != EOF);

	t = lx->buf;

	assert(t != NULL);

	if (t->p == t->a + t->len) {
		size_t len;
		char *tmp;

		if (t->len == 0) {
			assert(LX_DYN_LOW > 0);
			len = LX_DYN_LOW;
		} else {
			len = t->len * LX_DYN_FACTOR;
			if (len < t->len) {
				errno = ERANGE;
				return -1;
			}
		}

		tmp = realloc(t->a, len);
		if (tmp == NULL) {
			return -1;
		}

		t->p   = tmp + (t->p - t->a);
		t->a   = tmp;
		t->len = len;
	}

	assert(t->p != NULL);
	assert(t->a != NULL);

	*t->p++ = c;

	return 0;
}

void
lx_simple_dynpop(struct lx_simple_lx *lx)
{
	struct lx_dynbuf *t;

	assert(lx != NULL);

	t = lx->buf;

	assert(t != NULL);
	assert(t->a != NULL);
	assert(t->p >= t->a);

	if (t->p == t->a) {
		return;
	}

	t->p--;
}

int
lx_simple_dynclear(struct lx_simple_lx *lx)
{
	struct lx_dynbuf *t;

	assert(lx != NULL);

	t = lx->buf;

	assert(t != NULL);

	if (t->len > LX_DYN_HIGH) {
		size_t len;
		char *tmp;

		len = t->len / LX_DYN_FACTOR;

		tmp = realloc(t->a, len);
		if (tmp == NULL) {
			return -1;
		}

		t->a   = tmp;
		t->len = len;
	}

	t->p = t->a;

	return 0;
}

void
lx_simple_dynfree(struct lx_simple_lx *lx)
{
	struct lx_dynbuf *t;

	assert(lx != NULL);

	t = lx->buf;

	assert(t != NULL);

	free(t->a);
}
int
lx_simple_fixedpush(struct lx_simple_lx *lx, char c)
{
	struct lx_fixedbuf *t;

	assert(lx != NULL);
	assert(c != EOF);

	t = lx->buf;

	assert(t != NULL);
	assert(t->p != NULL);
	assert(t->a != NULL);

	if (t->p == t->a + t->len) {
		errno = ENOMEM;
		return -1;
	}

	*t->p++ = c;

	return 0;
}

void
lx_simple_fixedpop(struct lx_simple_lx *lx)
{
	struct lx_fixedbuf *t;

	assert(lx != NULL);

	t = lx->buf;

	assert(t != NULL);
	assert(t->a != NULL);
	assert(t->p >= t->a);

	if (t->p == t->a) {
		return;
	}

	t->p--;
}

int
lx_simple_fixedclear(struct lx_simple_lx *lx)
{
	struct lx_fixedbuf *t;

	assert(lx != NULL);

	t = lx->buf;

	assert(t != NULL);
	assert(t->p != NULL);
	assert(t->a != NULL);

	t->p = t->a;

	return 0;
}

static enum lx_simple_token
z1(struct lx_simple_lx *lx)
{
	int c;

	enum {
		S1, S2, S3, S4
	} state;

	assert(lx != NULL);

	if (lx->clear != NULL) {
		lx->clear(lx);
	}

	state = S4;

	lx->start = lx->end;

	while (c = lx_getc(lx), c != EOF) {
		switch (state) {
			break;

		default:
			if (lx->push != NULL) {
				if (-1 == lx->push(lx, c)) {
					return TOK_ERROR;
				}
			}
			break;

		}

		switch (state) {
		case S1: /* e.g. "," */
			switch (c) {
			default:  lx_simple_ungetc(lx, c); return TOK_SEP;
			}

		case S2: /* e.g. "0" */
			switch (c) {
			case '0':	          continue;
			case '1':	          continue;
			case '2':	          continue;
			case '3':	          continue;
			case '4':	          continue;
			case '5':	          continue;
			case '6':	          continue;
			case '7':	          continue;
			case '8':	          continue;
			case '9':	          continue;
			default:  lx_simple_ungetc(lx, c); return TOK_COUNT;
			}

		case S3: /* e.g. "}" */
			switch (c) {
			default:  lx_simple_ungetc(lx, c); return lx->z = z3, TOK_CLOSECOUNT;
			}

		case S4: /* start */
			switch (c) {
			case ',': state = S1;      continue;
			case '0': state = S2;      continue;
			case '1': state = S2;      continue;
			case '2': state = S2;      continue;
			case '3': state = S2;      continue;
			case '4': state = S2;      continue;
			case '5': state = S2;      continue;
			case '6': state = S2;      continue;
			case '7': state = S2;      continue;
			case '8': state = S2;      continue;
			case '9': state = S2;      continue;
			case '}': state = S3;      continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}
		}
	}

	lx->lgetc = NULL;

	switch (state) {
	case S1: return TOK_SEP;
	case S2: return TOK_COUNT;
	case S3: return TOK_CLOSECOUNT;
	default: errno = EINVAL; return TOK_ERROR;
	}
}

static enum lx_simple_token
z2(struct lx_simple_lx *lx)
{
	int c;

	enum {
		S1, S2, S3, S4, S5, S6, S7, S8, S9, S10
		
	} state;

	assert(lx != NULL);

	if (lx->clear != NULL) {
		lx->clear(lx);
	}

	state = S10;

	lx->start = lx->end;

	while (c = lx_getc(lx), c != EOF) {
		switch (state) {
			break;

		default:
			if (lx->push != NULL) {
				if (-1 == lx->push(lx, c)) {
					return TOK_ERROR;
				}
			}
			break;

		}

		switch (state) {
		case S1: /* e.g. "\\xa" */
			switch (c) {
			case '0':	          continue;
			case '1':	          continue;
			case '2':	          continue;
			case '3':	          continue;
			case '4':	          continue;
			case '5':	          continue;
			case '6':	          continue;
			case '7':	          continue;
			case '8':	          continue;
			case '9':	          continue;
			case 'A':	          continue;
			case 'B':	          continue;
			case 'C':	          continue;
			case 'D':	          continue;
			case 'E':	          continue;
			case 'F':	          continue;
			case 'a':	          continue;
			case 'b':	          continue;
			case 'c':	          continue;
			case 'd':	          continue;
			case 'e':	          continue;
			case 'f':	          continue;
			default:  lx_simple_ungetc(lx, c); return TOK_HEX;
			}

		case S2: /* e.g. "\\x" */
			switch (c) {
			case '0': state = S1;      continue;
			case '1': state = S1;      continue;
			case '2': state = S1;      continue;
			case '3': state = S1;      continue;
			case '4': state = S1;      continue;
			case '5': state = S1;      continue;
			case '6': state = S1;      continue;
			case '7': state = S1;      continue;
			case '8': state = S1;      continue;
			case '9': state = S1;      continue;
			case 'A': state = S1;      continue;
			case 'B': state = S1;      continue;
			case 'C': state = S1;      continue;
			case 'D': state = S1;      continue;
			case 'E': state = S1;      continue;
			case 'F': state = S1;      continue;
			case 'a': state = S1;      continue;
			case 'b': state = S1;      continue;
			case 'c': state = S1;      continue;
			case 'd': state = S1;      continue;
			case 'e': state = S1;      continue;
			case 'f': state = S1;      continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S3: /* e.g. "\\0" */
			switch (c) {
			case '0':	          continue;
			case '1':	          continue;
			case '2':	          continue;
			case '3':	          continue;
			case '4':	          continue;
			case '5':	          continue;
			case '6':	          continue;
			case '7':	          continue;
			default:  lx_simple_ungetc(lx, c); return TOK_OCT;
			}

		case S4: /* e.g. "\\f" */
			switch (c) {
			default:  lx_simple_ungetc(lx, c); return TOK_ESC;
			}

		case S5: /* e.g. "-" */
			switch (c) {
			default:  lx_simple_ungetc(lx, c); return TOK_RANGE;
			}

		case S6: /* e.g. "\\" */
			switch (c) {
			case '-': state = S4;      continue;
			case '0': state = S3;      continue;
			case '1': state = S3;      continue;
			case '2': state = S3;      continue;
			case '3': state = S3;      continue;
			case '4': state = S3;      continue;
			case '5': state = S3;      continue;
			case '6': state = S3;      continue;
			case '7': state = S3;      continue;
			case '\\': state = S4;      continue;
			case '^': state = S4;      continue;
			case 'f': state = S4;      continue;
			case 'n': state = S4;      continue;
			case 'r': state = S4;      continue;
			case 't': state = S4;      continue;
			case 'v': state = S4;      continue;
			case 'x': state = S2;      continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S7: /* e.g. "]" */
			switch (c) {
			default:  lx_simple_ungetc(lx, c); return lx->z = z3, TOK_CLOSEGROUP;
			}

		case S8: /* e.g. "^" */
			switch (c) {
			default:  lx_simple_ungetc(lx, c); return TOK_INVERT;
			}

		case S9: /* e.g. "a" */
			switch (c) {
			default:  lx_simple_ungetc(lx, c); return TOK_CHAR;
			}

		case S10: /* start */
			switch (c) {
			case '-': state = S5;      continue;
			case '\\': state = S6;      continue;
			case ']': state = S7;      continue;
			case '^': state = S8;      continue;
			default:  state = S9;     continue;
			}
		}
	}

	lx->lgetc = NULL;

	switch (state) {
	case S1: return TOK_HEX;
	case S3: return TOK_OCT;
	case S4: return TOK_ESC;
	case S5: return TOK_RANGE;
	case S7: return TOK_CLOSEGROUP;
	case S8: return TOK_INVERT;
	case S9: return TOK_CHAR;
	default: errno = EINVAL; return TOK_ERROR;
	}
}

static enum lx_simple_token
z3(struct lx_simple_lx *lx)
{
	int c;

	enum {
		S1, S2, S3, S4, S5, S6, S7, S8, S9, S10, 
		S11, S12, S13, S14, S15, S16, S17, S18
	} state;

	assert(lx != NULL);

	if (lx->clear != NULL) {
		lx->clear(lx);
	}

	state = S18;

	lx->start = lx->end;

	while (c = lx_getc(lx), c != EOF) {
		switch (state) {
			break;

		default:
			if (lx->push != NULL) {
				if (-1 == lx->push(lx, c)) {
					return TOK_ERROR;
				}
			}
			break;

		}

		switch (state) {
		case S1: /* e.g. "\\xa" */
			switch (c) {
			case '0':	          continue;
			case '1':	          continue;
			case '2':	          continue;
			case '3':	          continue;
			case '4':	          continue;
			case '5':	          continue;
			case '6':	          continue;
			case '7':	          continue;
			case '8':	          continue;
			case '9':	          continue;
			case 'A':	          continue;
			case 'B':	          continue;
			case 'C':	          continue;
			case 'D':	          continue;
			case 'E':	          continue;
			case 'F':	          continue;
			case 'a':	          continue;
			case 'b':	          continue;
			case 'c':	          continue;
			case 'd':	          continue;
			case 'e':	          continue;
			case 'f':	          continue;
			default:  lx_simple_ungetc(lx, c); return TOK_HEX;
			}

		case S2: /* e.g. "\\x" */
			switch (c) {
			case '0': state = S1;      continue;
			case '1': state = S1;      continue;
			case '2': state = S1;      continue;
			case '3': state = S1;      continue;
			case '4': state = S1;      continue;
			case '5': state = S1;      continue;
			case '6': state = S1;      continue;
			case '7': state = S1;      continue;
			case '8': state = S1;      continue;
			case '9': state = S1;      continue;
			case 'A': state = S1;      continue;
			case 'B': state = S1;      continue;
			case 'C': state = S1;      continue;
			case 'D': state = S1;      continue;
			case 'E': state = S1;      continue;
			case 'F': state = S1;      continue;
			case 'a': state = S1;      continue;
			case 'b': state = S1;      continue;
			case 'c': state = S1;      continue;
			case 'd': state = S1;      continue;
			case 'e': state = S1;      continue;
			case 'f': state = S1;      continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S3: /* e.g. "\\0" */
			switch (c) {
			case '0':	          continue;
			case '1':	          continue;
			case '2':	          continue;
			case '3':	          continue;
			case '4':	          continue;
			case '5':	          continue;
			case '6':	          continue;
			case '7':	          continue;
			default:  lx_simple_ungetc(lx, c); return TOK_OCT;
			}

		case S4: /* e.g. "\\f" */
			switch (c) {
			default:  lx_simple_ungetc(lx, c); return TOK_ESC;
			}

		case S5: /* e.g. "$" */
			switch (c) {
			default:  lx_simple_ungetc(lx, c); return TOK_END;
			}

		case S6: /* e.g. "(" */
			switch (c) {
			default:  lx_simple_ungetc(lx, c); return TOK_OPENSUB;
			}

		case S7: /* e.g. ")" */
			switch (c) {
			default:  lx_simple_ungetc(lx, c); return TOK_CLOSESUB;
			}

		case S8: /* e.g. "*" */
			switch (c) {
			default:  lx_simple_ungetc(lx, c); return TOK_STAR;
			}

		case S9: /* e.g. "+" */
			switch (c) {
			default:  lx_simple_ungetc(lx, c); return TOK_PLUS;
			}

		case S10: /* e.g. "." */
			switch (c) {
			default:  lx_simple_ungetc(lx, c); return TOK_DOT;
			}

		case S11: /* e.g. "?" */
			switch (c) {
			default:  lx_simple_ungetc(lx, c); return TOK_QMARK;
			}

		case S12: /* e.g. "[" */
			switch (c) {
			default:  lx_simple_ungetc(lx, c); return lx->z = z2, TOK_OPENGROUP;
			}

		case S13: /* e.g. "\\" */
			switch (c) {
			case '$': state = S4;      continue;
			case '(': state = S4;      continue;
			case ')': state = S4;      continue;
			case '*': state = S4;      continue;
			case '+': state = S4;      continue;
			case '.': state = S4;      continue;
			case '0': state = S3;      continue;
			case '1': state = S3;      continue;
			case '2': state = S3;      continue;
			case '3': state = S3;      continue;
			case '4': state = S3;      continue;
			case '5': state = S3;      continue;
			case '6': state = S3;      continue;
			case '7': state = S3;      continue;
			case '?': state = S4;      continue;
			case '[': state = S4;      continue;
			case '\\': state = S4;      continue;
			case '^': state = S4;      continue;
			case 'f': state = S4;      continue;
			case 'n': state = S4;      continue;
			case 'r': state = S4;      continue;
			case 't': state = S4;      continue;
			case 'v': state = S4;      continue;
			case 'x': state = S2;      continue;
			case '{': state = S4;      continue;
			case '|': state = S4;      continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S14: /* e.g. "^" */
			switch (c) {
			default:  lx_simple_ungetc(lx, c); return TOK_START;
			}

		case S15: /* e.g. "{" */
			switch (c) {
			default:  lx_simple_ungetc(lx, c); return lx->z = z1, TOK_OPENCOUNT;
			}

		case S16: /* e.g. "|" */
			switch (c) {
			default:  lx_simple_ungetc(lx, c); return TOK_ALT;
			}

		case S17: /* e.g. "a" */
			switch (c) {
			default:  lx_simple_ungetc(lx, c); return TOK_CHAR;
			}

		case S18: /* start */
			switch (c) {
			case '$': state = S5;      continue;
			case '(': state = S6;      continue;
			case ')': state = S7;      continue;
			case '*': state = S8;      continue;
			case '+': state = S9;      continue;
			case '.': state = S10;      continue;
			case '?': state = S11;      continue;
			case '[': state = S12;      continue;
			case '\\': state = S13;      continue;
			case '^': state = S14;      continue;
			case '{': state = S15;      continue;
			case '|': state = S16;      continue;
			default:  state = S17;     continue;
			}
		}
	}

	lx->lgetc = NULL;

	switch (state) {
	case S1: return TOK_HEX;
	case S3: return TOK_OCT;
	case S4: return TOK_ESC;
	case S5: return TOK_END;
	case S6: return TOK_OPENSUB;
	case S7: return TOK_CLOSESUB;
	case S8: return TOK_STAR;
	case S9: return TOK_PLUS;
	case S10: return TOK_DOT;
	case S11: return TOK_QMARK;
	case S12: return TOK_OPENGROUP;
	case S14: return TOK_START;
	case S15: return TOK_OPENCOUNT;
	case S16: return TOK_ALT;
	case S17: return TOK_CHAR;
	default: errno = EINVAL; return TOK_ERROR;
	}
}

const char *
lx_simple_name(enum lx_simple_token t)
{
	switch (t) {
	case TOK_CLOSECOUNT: return "CLOSECOUNT";
	case TOK_OPENCOUNT: return "OPENCOUNT";
	case TOK_COUNT: return "COUNT";
	case TOK_SEP: return "SEP";
	case TOK_CLOSEGROUP: return "CLOSEGROUP";
	case TOK_OPENGROUP: return "OPENGROUP";
	case TOK_RANGE: return "RANGE";
	case TOK_INVERT: return "INVERT";
	case TOK_CHAR: return "CHAR";
	case TOK_HEX: return "HEX";
	case TOK_OCT: return "OCT";
	case TOK_ESC: return "ESC";
	case TOK_ALT: return "ALT";
	case TOK_DOT: return "DOT";
	case TOK_PLUS: return "PLUS";
	case TOK_STAR: return "STAR";
	case TOK_QMARK: return "QMARK";
	case TOK_END: return "END";
	case TOK_START: return "START";
	case TOK_CLOSESUB: return "CLOSESUB";
	case TOK_OPENSUB: return "OPENSUB";
	case TOK_EOF:     return "EOF";
	case TOK_ERROR:   return "ERROR";
	case TOK_UNKNOWN: return "UNKNOWN";
	default: return "?";
	}
}

const char *
lx_simple_example(enum lx_simple_token (*z)(struct lx_simple_lx *), enum lx_simple_token t)
{
	assert(z != NULL);

	if (z == z1) {
		switch (t) {
		case TOK_CLOSECOUNT: return "}";
		case TOK_COUNT: return "0";
		case TOK_SEP: return ",";
		default: goto error;
		}
	} else
	if (z == z2) {
		switch (t) {
		case TOK_CLOSEGROUP: return "]";
		case TOK_RANGE: return "-";
		case TOK_INVERT: return "^";
		case TOK_CHAR: return "a";
		case TOK_HEX: return "\\xa";
		case TOK_OCT: return "\\0";
		case TOK_ESC: return "\\f";
		default: goto error;
		}
	} else
	if (z == z3) {
		switch (t) {
		case TOK_OPENCOUNT: return "{";
		case TOK_OPENGROUP: return "[";
		case TOK_CHAR: return "a";
		case TOK_HEX: return "\\xa";
		case TOK_OCT: return "\\0";
		case TOK_ESC: return "\\f";
		case TOK_ALT: return "|";
		case TOK_DOT: return ".";
		case TOK_PLUS: return "+";
		case TOK_STAR: return "*";
		case TOK_QMARK: return "?";
		case TOK_END: return "$";
		case TOK_START: return "^";
		case TOK_CLOSESUB: return ")";
		case TOK_OPENSUB: return "(";
		default: goto error;
		}
	}

error:

	errno = EINVAL;
	return NULL;
}

void
lx_simple_init(struct lx_simple_lx *lx)
{
	static const struct lx_simple_lx lx_default;

	assert(lx != NULL);

	*lx = lx_default;

	lx->c = EOF;
	lx->z = NULL;

	lx->end.byte = 0;
	lx->end.line = 1;
	lx->end.col  = 1;
}

enum lx_simple_token
lx_simple_next(struct lx_simple_lx *lx)
{
	enum lx_simple_token t;

	assert(lx != NULL);

	if (lx->lgetc == NULL) {
		return TOK_EOF;
	}

	if (lx->z == NULL) {
		lx->z = z3;
	}

	t = lx->z(lx);

	if (lx->push != NULL) {
		if (-1 == lx->push(lx, '\0')) {
			return TOK_ERROR;
		}
	}

	if (lx->lgetc == NULL && lx->free != NULL) {
		lx->free(lx);
	}

	return t;
}

