# $Id$

.include "Makefile.inc"


CFLAGS+= -I ${BASE_DIR}/src
CFLAGS+= -I ${BASE_DIR}/include

# iterators
SRCS+= count.c
SRCS+= has.c
SRCS+= all.c
SRCS+= reachable.c

.include <lx.obj.mk>

.include <lx.partial.mk>

