/* Generated by libfsm */

#include LF_HEADER

#include <stddef.h>

#include <fsm/fsm.h>

struct fsm *
utf8_Hangul_fsm(const struct fsm_options *opt)
{
	struct fsm *fsm;
	size_t i;

	struct fsm_state *s[18] = { 0 };

	fsm = fsm_new(opt);
	if (fsm == NULL) {
		return NULL;
	}

	for (i = 0; i < 18; i++) {
		s[i] = fsm_addstate(fsm);
		if (s[i] == NULL) {
			goto error;
		}
	}

	if (!fsm_addedge_literal(fsm, s[0], s[1], 0xe1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[2], 0xe3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[3], 0xea)) { goto error; }
	for (i = 0xeb; i <= 0xec; i++) {
		if (!fsm_addedge_literal(fsm, s[0], s[4], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[0], s[5], 0xed)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[6], 0xef)) { goto error; }
	for (i = 0x84; i <= 0x87; i++) {
		if (!fsm_addedge_literal(fsm, s[1], s[12], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[2], s[7], 0x89)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[2], s[10], 0x80)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[2], s[11], 0x84)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[2], s[12], 0x85)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[2], s[13], 0x86)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[2], s[14], 0x88)) { goto error; }
	for (i = 0xb0; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[12], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[3], s[15], 0xa5)) { goto error; }
	for (i = 0x80; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[4], s[12], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x9d; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[12], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[5], s[16], 0x9e)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[5], s[17], 0x9f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[7], 0xbe)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[8], 0xbf)) { goto error; }
	for (i = 0xa0; i <= 0xbe; i++) {
		if (!fsm_addedge_literal(fsm, s[7], s[9], i)) { goto error; }
	}
	for (i = 0x82; i <= 0x87; i++) {
		if (!fsm_addedge_literal(fsm, s[8], s[9], i)) { goto error; }
	}
	for (i = 0x8a; i <= 0x8f; i++) {
		if (!fsm_addedge_literal(fsm, s[8], s[9], i)) { goto error; }
	}
	for (i = 0x92; i <= 0x97; i++) {
		if (!fsm_addedge_literal(fsm, s[8], s[9], i)) { goto error; }
	}
	for (i = 0x9a; i <= 0x9c; i++) {
		if (!fsm_addedge_literal(fsm, s[8], s[9], i)) { goto error; }
	}
	for (i = 0xae; i <= 0xaf; i++) {
		if (!fsm_addedge_literal(fsm, s[10], s[9], i)) { goto error; }
	}
	for (i = 0xb1; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[11], s[9], i)) { goto error; }
	}
	for (i = 0x80; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[12], s[9], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x8e; i++) {
		if (!fsm_addedge_literal(fsm, s[13], s[9], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x9e; i++) {
		if (!fsm_addedge_literal(fsm, s[14], s[9], i)) { goto error; }
	}
	for (i = 0xa0; i <= 0xbc; i++) {
		if (!fsm_addedge_literal(fsm, s[15], s[9], i)) { goto error; }
	}
	for (i = 0x80; i <= 0xa3; i++) {
		if (!fsm_addedge_literal(fsm, s[16], s[9], i)) { goto error; }
	}
	for (i = 0xb0; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[16], s[9], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x86; i++) {
		if (!fsm_addedge_literal(fsm, s[17], s[9], i)) { goto error; }
	}
	for (i = 0x8b; i <= 0xbb; i++) {
		if (!fsm_addedge_literal(fsm, s[17], s[9], i)) { goto error; }
	}

	fsm_setstart(fsm, s[0]);
	fsm_setend(fsm, s[9], 1);

	return fsm;

error:

	fsm_free(fsm);

	return NULL;
}

