/* Generated by libfsm */

#include LF_HEADER

#include <assert.h>
#include <stddef.h>

#include <fsm/fsm.h>

int
utf8_Cs_fsm(struct fsm *fsm, struct fsm_state *x, struct fsm_state *y)
{
	struct fsm_state *s[1];
	size_t i;

	assert(x != NULL);
	assert(y != NULL);

	for (i = 0; i < 1; i++) {
		if (i == 0) {
			s[0] = x;
			continue;
		}

		s[i] = fsm_addstate(fsm);
		if (s[i] == NULL) {
			return 0;
		}
	}

	return 1;
}

