/* Generated by libfsm */

#include LF_HEADER

#include <assert.h>
#include <stddef.h>

#include <fsm/fsm.h>

int
utf8_Mc_fsm(struct fsm *fsm, struct fsm_state *x, struct fsm_state *y)
{
	struct fsm_state *s[73];
	size_t i;

	assert(x != NULL);
	assert(y != NULL);

	for (i = 0; i < 73; i++) {
		if (i == 0) {
			s[0] = x;
			continue;
		}

		if (i == 20) {
			s[20] = y;
			continue;
		}

		s[i] = fsm_addstate(fsm);
		if (s[i] == NULL) {
			return 0;
		}
	}

	if (!fsm_addedge_literal(fsm, s[0], s[1], 0xe0)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[0], s[2], 0xe1)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[0], s[3], 0xe3)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[0], s[4], 0xea)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[0], s[5], 0xf0)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[1], s[14], 0xa9)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[1], s[23], 0xa4)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[1], s[24], 0xa5)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[1], s[25], 0xa6)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[1], s[25], 0xb4)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[1], s[26], 0xa7)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[1], s[26], 0xad)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[1], s[27], 0xa8)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[1], s[27], 0xaa)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[1], s[28], 0xab)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[1], s[29], 0xac)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[1], s[29], 0xb2)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[1], s[30], 0xae)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[1], s[30], 0xbc)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[1], s[31], 0xaf)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[1], s[32], 0xb0)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[1], s[33], 0xb1)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[1], s[34], 0xb3)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[1], s[35], 0xb5)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[1], s[36], 0xb6)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[1], s[37], 0xb7)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[1], s[38], 0xbd)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[2], s[39], 0x80)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[2], s[40], 0x81)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[2], s[41], 0x82)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[2], s[42], 0x9e)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[2], s[43], 0x9f)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[2], s[44], 0xa4)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[2], s[45], 0xa8)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[2], s[46], 0xa9)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[2], s[47], 0xac)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[2], s[48], 0xad)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[2], s[49], 0xae)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[2], s[50], 0xaf)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[2], s[51], 0xb0)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[2], s[52], 0xb3)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[3], s[21], 0x80)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[4], s[9], 0xa0)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[4], s[10], 0xa2)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[4], s[11], 0xa3)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[4], s[12], 0xa5)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[4], s[13], 0xa6)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[4], s[14], 0xa7)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[4], s[15], 0xa8)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[4], s[16], 0xa9)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[4], s[17], 0xab)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[4], s[18], 0xaf)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[5], s[6], 0x91)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[5], s[7], 0x96)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[5], s[8], 0x9d)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[6], s[14], 0x87)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[6], s[25], 0x8c)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[6], s[53], 0x80)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[6], s[54], 0x82)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[6], s[55], 0x84)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[6], s[56], 0x86)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[6], s[57], 0x88)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[6], s[58], 0x8b)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[6], s[59], 0x8d)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[6], s[60], 0x90)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[6], s[61], 0x91)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[6], s[62], 0x92)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[6], s[63], 0x93)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[6], s[64], 0x96)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[6], s[65], 0x98)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[6], s[66], 0x9a)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[6], s[67], 0x9c)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[6], s[68], 0xa8)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[6], s[69], 0xa9)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[6], s[70], 0xaa)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[6], s[71], 0xb0)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[6], s[72], 0xb2)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[7], s[22], 0xbd)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[8], s[19], 0x85)) { return 0; }
	for (i = 0xa3; i <= 0xa4; i++) {
		if (!fsm_addedge_literal(fsm, s[9], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[9], s[20], 0xa7)) { return 0; }
	for (i = 0x80; i <= 0x81; i++) {
		if (!fsm_addedge_literal(fsm, s[10], s[20], i)) { return 0; }
	}
	for (i = 0xb4; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[10], s[20], i)) { return 0; }
	}
	for (i = 0x80; i <= 0x83; i++) {
		if (!fsm_addedge_literal(fsm, s[11], s[20], i)) { return 0; }
	}
	for (i = 0x92; i <= 0x93; i++) {
		if (!fsm_addedge_literal(fsm, s[12], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[13], s[20], 0x83)) { return 0; }
	for (i = 0xb4; i <= 0xb5; i++) {
		if (!fsm_addedge_literal(fsm, s[13], s[20], i)) { return 0; }
	}
	for (i = 0xba; i <= 0xbb; i++) {
		if (!fsm_addedge_literal(fsm, s[13], s[20], i)) { return 0; }
	}
	for (i = 0xbd; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[13], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[14], s[20], 0x80)) { return 0; }
	for (i = 0xaf; i <= 0xb0; i++) {
		if (!fsm_addedge_literal(fsm, s[15], s[20], i)) { return 0; }
	}
	for (i = 0xb3; i <= 0xb4; i++) {
		if (!fsm_addedge_literal(fsm, s[15], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[16], s[20], 0x8d)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[16], s[20], 0xbb)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[16], s[20], 0xbd)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[17], s[20], 0xab)) { return 0; }
	for (i = 0xae; i <= 0xaf; i++) {
		if (!fsm_addedge_literal(fsm, s[17], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[17], s[20], 0xb5)) { return 0; }
	for (i = 0xa3; i <= 0xa4; i++) {
		if (!fsm_addedge_literal(fsm, s[18], s[20], i)) { return 0; }
	}
	for (i = 0xa6; i <= 0xa7; i++) {
		if (!fsm_addedge_literal(fsm, s[18], s[20], i)) { return 0; }
	}
	for (i = 0xa9; i <= 0xaa; i++) {
		if (!fsm_addedge_literal(fsm, s[18], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[18], s[20], 0xac)) { return 0; }
	for (i = 0xa5; i <= 0xa6; i++) {
		if (!fsm_addedge_literal(fsm, s[19], s[20], i)) { return 0; }
	}
	for (i = 0xad; i <= 0xb2; i++) {
		if (!fsm_addedge_literal(fsm, s[19], s[20], i)) { return 0; }
	}
	for (i = 0xae; i <= 0xaf; i++) {
		if (!fsm_addedge_literal(fsm, s[21], s[20], i)) { return 0; }
	}
	for (i = 0x91; i <= 0xbe; i++) {
		if (!fsm_addedge_literal(fsm, s[22], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[23], s[20], 0x83)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[23], s[20], 0xbb)) { return 0; }
	for (i = 0xbe; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[23], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[24], s[20], 0x80)) { return 0; }
	for (i = 0x89; i <= 0x8c; i++) {
		if (!fsm_addedge_literal(fsm, s[24], s[20], i)) { return 0; }
	}
	for (i = 0x8e; i <= 0x8f; i++) {
		if (!fsm_addedge_literal(fsm, s[24], s[20], i)) { return 0; }
	}
	for (i = 0x82; i <= 0x83; i++) {
		if (!fsm_addedge_literal(fsm, s[25], s[20], i)) { return 0; }
	}
	for (i = 0xbe; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[25], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[26], s[20], 0x80)) { return 0; }
	for (i = 0x87; i <= 0x88; i++) {
		if (!fsm_addedge_literal(fsm, s[26], s[20], i)) { return 0; }
	}
	for (i = 0x8b; i <= 0x8c; i++) {
		if (!fsm_addedge_literal(fsm, s[26], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[26], s[20], 0x97)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[27], s[20], 0x83)) { return 0; }
	for (i = 0xbe; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[27], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[28], s[20], 0x80)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[28], s[20], 0x89)) { return 0; }
	for (i = 0x8b; i <= 0x8c; i++) {
		if (!fsm_addedge_literal(fsm, s[28], s[20], i)) { return 0; }
	}
	for (i = 0x82; i <= 0x83; i++) {
		if (!fsm_addedge_literal(fsm, s[29], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[29], s[20], 0xbe)) { return 0; }
	for (i = 0xbe; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[30], s[20], i)) { return 0; }
	}
	for (i = 0x81; i <= 0x82; i++) {
		if (!fsm_addedge_literal(fsm, s[31], s[20], i)) { return 0; }
	}
	for (i = 0x86; i <= 0x88; i++) {
		if (!fsm_addedge_literal(fsm, s[31], s[20], i)) { return 0; }
	}
	for (i = 0x8a; i <= 0x8c; i++) {
		if (!fsm_addedge_literal(fsm, s[31], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[31], s[20], 0x97)) { return 0; }
	for (i = 0x81; i <= 0x83; i++) {
		if (!fsm_addedge_literal(fsm, s[32], s[20], i)) { return 0; }
	}
	for (i = 0x81; i <= 0x84; i++) {
		if (!fsm_addedge_literal(fsm, s[33], s[20], i)) { return 0; }
	}
	for (i = 0x80; i <= 0x84; i++) {
		if (!fsm_addedge_literal(fsm, s[34], s[20], i)) { return 0; }
	}
	for (i = 0x87; i <= 0x88; i++) {
		if (!fsm_addedge_literal(fsm, s[34], s[20], i)) { return 0; }
	}
	for (i = 0x8a; i <= 0x8b; i++) {
		if (!fsm_addedge_literal(fsm, s[34], s[20], i)) { return 0; }
	}
	for (i = 0x95; i <= 0x96; i++) {
		if (!fsm_addedge_literal(fsm, s[34], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[35], s[20], 0x80)) { return 0; }
	for (i = 0x86; i <= 0x88; i++) {
		if (!fsm_addedge_literal(fsm, s[35], s[20], i)) { return 0; }
	}
	for (i = 0x8a; i <= 0x8c; i++) {
		if (!fsm_addedge_literal(fsm, s[35], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[35], s[20], 0x97)) { return 0; }
	for (i = 0x82; i <= 0x83; i++) {
		if (!fsm_addedge_literal(fsm, s[36], s[20], i)) { return 0; }
	}
	for (i = 0x8f; i <= 0x91; i++) {
		if (!fsm_addedge_literal(fsm, s[37], s[20], i)) { return 0; }
	}
	for (i = 0x98; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[37], s[20], i)) { return 0; }
	}
	for (i = 0xb2; i <= 0xb3; i++) {
		if (!fsm_addedge_literal(fsm, s[37], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[38], s[20], 0xbf)) { return 0; }
	for (i = 0xab; i <= 0xac; i++) {
		if (!fsm_addedge_literal(fsm, s[39], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[39], s[20], 0xb1)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[39], s[20], 0xb8)) { return 0; }
	for (i = 0xbb; i <= 0xbc; i++) {
		if (!fsm_addedge_literal(fsm, s[39], s[20], i)) { return 0; }
	}
	for (i = 0x96; i <= 0x97; i++) {
		if (!fsm_addedge_literal(fsm, s[40], s[20], i)) { return 0; }
	}
	for (i = 0xa2; i <= 0xa4; i++) {
		if (!fsm_addedge_literal(fsm, s[40], s[20], i)) { return 0; }
	}
	for (i = 0xa7; i <= 0xad; i++) {
		if (!fsm_addedge_literal(fsm, s[40], s[20], i)) { return 0; }
	}
	for (i = 0x83; i <= 0x84; i++) {
		if (!fsm_addedge_literal(fsm, s[41], s[20], i)) { return 0; }
	}
	for (i = 0x87; i <= 0x8c; i++) {
		if (!fsm_addedge_literal(fsm, s[41], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[41], s[20], 0x8f)) { return 0; }
	for (i = 0x9a; i <= 0x9c; i++) {
		if (!fsm_addedge_literal(fsm, s[41], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[42], s[20], 0xb6)) { return 0; }
	for (i = 0xbe; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[42], s[20], i)) { return 0; }
	}
	for (i = 0x80; i <= 0x85; i++) {
		if (!fsm_addedge_literal(fsm, s[43], s[20], i)) { return 0; }
	}
	for (i = 0x87; i <= 0x88; i++) {
		if (!fsm_addedge_literal(fsm, s[43], s[20], i)) { return 0; }
	}
	for (i = 0xa3; i <= 0xa6; i++) {
		if (!fsm_addedge_literal(fsm, s[44], s[20], i)) { return 0; }
	}
	for (i = 0xa9; i <= 0xab; i++) {
		if (!fsm_addedge_literal(fsm, s[44], s[20], i)) { return 0; }
	}
	for (i = 0xb0; i <= 0xb1; i++) {
		if (!fsm_addedge_literal(fsm, s[44], s[20], i)) { return 0; }
	}
	for (i = 0xb3; i <= 0xb8; i++) {
		if (!fsm_addedge_literal(fsm, s[44], s[20], i)) { return 0; }
	}
	for (i = 0x99; i <= 0x9a; i++) {
		if (!fsm_addedge_literal(fsm, s[45], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[46], s[20], 0x95)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[46], s[20], 0x97)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[46], s[20], 0xa1)) { return 0; }
	for (i = 0xa3; i <= 0xa4; i++) {
		if (!fsm_addedge_literal(fsm, s[46], s[20], i)) { return 0; }
	}
	for (i = 0xad; i <= 0xb2; i++) {
		if (!fsm_addedge_literal(fsm, s[46], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[47], s[20], 0x84)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[47], s[20], 0xb5)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[47], s[20], 0xbb)) { return 0; }
	for (i = 0xbd; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[47], s[20], i)) { return 0; }
	}
	for (i = 0x80; i <= 0x81; i++) {
		if (!fsm_addedge_literal(fsm, s[48], s[20], i)) { return 0; }
	}
	for (i = 0x83; i <= 0x84; i++) {
		if (!fsm_addedge_literal(fsm, s[48], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[49], s[20], 0x82)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[49], s[20], 0xa1)) { return 0; }
	for (i = 0xa6; i <= 0xa7; i++) {
		if (!fsm_addedge_literal(fsm, s[49], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[49], s[20], 0xaa)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[50], s[20], 0xa7)) { return 0; }
	for (i = 0xaa; i <= 0xac; i++) {
		if (!fsm_addedge_literal(fsm, s[50], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[50], s[20], 0xae)) { return 0; }
	for (i = 0xb2; i <= 0xb3; i++) {
		if (!fsm_addedge_literal(fsm, s[50], s[20], i)) { return 0; }
	}
	for (i = 0xa4; i <= 0xab; i++) {
		if (!fsm_addedge_literal(fsm, s[51], s[20], i)) { return 0; }
	}
	for (i = 0xb4; i <= 0xb5; i++) {
		if (!fsm_addedge_literal(fsm, s[51], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[52], s[20], 0xa1)) { return 0; }
	for (i = 0xb2; i <= 0xb3; i++) {
		if (!fsm_addedge_literal(fsm, s[52], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[52], s[20], 0xb7)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[53], s[20], 0x80)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[53], s[20], 0x82)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[54], s[20], 0x82)) { return 0; }
	for (i = 0xb0; i <= 0xb2; i++) {
		if (!fsm_addedge_literal(fsm, s[54], s[20], i)) { return 0; }
	}
	for (i = 0xb7; i <= 0xb8; i++) {
		if (!fsm_addedge_literal(fsm, s[54], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[55], s[20], 0xac)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[56], s[20], 0x82)) { return 0; }
	for (i = 0xb3; i <= 0xb5; i++) {
		if (!fsm_addedge_literal(fsm, s[56], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[56], s[20], 0xbf)) { return 0; }
	for (i = 0xac; i <= 0xae; i++) {
		if (!fsm_addedge_literal(fsm, s[57], s[20], i)) { return 0; }
	}
	for (i = 0xb2; i <= 0xb3; i++) {
		if (!fsm_addedge_literal(fsm, s[57], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[57], s[20], 0xb5)) { return 0; }
	for (i = 0xa0; i <= 0xa2; i++) {
		if (!fsm_addedge_literal(fsm, s[58], s[20], i)) { return 0; }
	}
	for (i = 0x81; i <= 0x84; i++) {
		if (!fsm_addedge_literal(fsm, s[59], s[20], i)) { return 0; }
	}
	for (i = 0x87; i <= 0x88; i++) {
		if (!fsm_addedge_literal(fsm, s[59], s[20], i)) { return 0; }
	}
	for (i = 0x8b; i <= 0x8d; i++) {
		if (!fsm_addedge_literal(fsm, s[59], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[59], s[20], 0x97)) { return 0; }
	for (i = 0xa2; i <= 0xa3; i++) {
		if (!fsm_addedge_literal(fsm, s[59], s[20], i)) { return 0; }
	}
	for (i = 0xb5; i <= 0xb7; i++) {
		if (!fsm_addedge_literal(fsm, s[60], s[20], i)) { return 0; }
	}
	for (i = 0x80; i <= 0x81; i++) {
		if (!fsm_addedge_literal(fsm, s[61], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[61], s[20], 0x85)) { return 0; }
	for (i = 0xb0; i <= 0xb2; i++) {
		if (!fsm_addedge_literal(fsm, s[62], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[62], s[20], 0xb9)) { return 0; }
	for (i = 0xbb; i <= 0xbe; i++) {
		if (!fsm_addedge_literal(fsm, s[62], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[63], s[20], 0x81)) { return 0; }
	for (i = 0xaf; i <= 0xb1; i++) {
		if (!fsm_addedge_literal(fsm, s[64], s[20], i)) { return 0; }
	}
	for (i = 0xb8; i <= 0xbb; i++) {
		if (!fsm_addedge_literal(fsm, s[64], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[64], s[20], 0xbe)) { return 0; }
	for (i = 0xb0; i <= 0xb2; i++) {
		if (!fsm_addedge_literal(fsm, s[65], s[20], i)) { return 0; }
	}
	for (i = 0xbb; i <= 0xbc; i++) {
		if (!fsm_addedge_literal(fsm, s[65], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[65], s[20], 0xbe)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[66], s[20], 0xac)) { return 0; }
	for (i = 0xae; i <= 0xaf; i++) {
		if (!fsm_addedge_literal(fsm, s[66], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[66], s[20], 0xb6)) { return 0; }
	for (i = 0xa0; i <= 0xa1; i++) {
		if (!fsm_addedge_literal(fsm, s[67], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[67], s[20], 0xa6)) { return 0; }
	for (i = 0x87; i <= 0x88; i++) {
		if (!fsm_addedge_literal(fsm, s[68], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[68], s[20], 0xb9)) { return 0; }
	for (i = 0x97; i <= 0x98; i++) {
		if (!fsm_addedge_literal(fsm, s[69], s[20], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[70], s[20], 0x97)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[71], s[20], 0xaf)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[71], s[20], 0xbe)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[72], s[20], 0xa9)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[72], s[20], 0xb1)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[72], s[20], 0xb4)) { return 0; }


	return 1;
}

