/* Generated by libfsm */

#include LF_HEADER

#include <assert.h>
#include <stddef.h>

#include <fsm/fsm.h>

int
utf8_Latin_fsm(struct fsm *fsm, struct fsm_state *x, struct fsm_state *y)
{
	struct fsm_state *s[28];
	size_t i;

	assert(x != NULL);
	assert(y != NULL);

	for (i = 0; i < 28; i++) {
		if (i == 0) {
			s[0] = x;
			continue;
		}

		if (i == 1) {
			s[1] = y;
			continue;
		}

		s[i] = fsm_addstate(fsm);
		if (s[i] == NULL) {
			return 0;
		}
	}

	for (i = 0x41; i <= 0x5a; i++) { /* 'A' .. 'Z' */
		if (!fsm_addedge_literal(fsm, s[0], s[1], i)) { return 0; }
	}
	for (i = 0x61; i <= 0x7a; i++) { /* 'a' .. 'z' */
		if (!fsm_addedge_literal(fsm, s[0], s[1], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[0], s[2], 0xc2)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[0], s[3], 0xc3)) { return 0; }
	for (i = 0xc4; i <= 0xc9; i++) {
		if (!fsm_addedge_literal(fsm, s[0], s[4], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[0], s[5], 0xca)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[0], s[6], 0xcb)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[0], s[7], 0xe1)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[0], s[8], 0xe2)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[0], s[9], 0xea)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[0], s[10], 0xef)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[2], s[1], 0xaa)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[2], s[1], 0xba)) { return 0; }
	for (i = 0x80; i <= 0x96; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[1], i)) { return 0; }
	}
	for (i = 0x98; i <= 0xb6; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[1], i)) { return 0; }
	}
	for (i = 0xb8; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[1], i)) { return 0; }
	}
	for (i = 0x80; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[4], s[1], i)) { return 0; }
	}
	for (i = 0x80; i <= 0xb8; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[1], i)) { return 0; }
	}
	for (i = 0xa0; i <= 0xa4; i++) {
		if (!fsm_addedge_literal(fsm, s[6], s[1], i)) { return 0; }
	}
	for (i = 0xb8; i <= 0xbb; i++) {
		if (!fsm_addedge_literal(fsm, s[7], s[4], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[7], s[11], 0xb4)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[7], s[12], 0xb5)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[7], s[13], 0xb6)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[8], s[14], 0x81)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[8], s[15], 0x82)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[8], s[16], 0x84)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[8], s[17], 0x85)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[8], s[18], 0x86)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[8], s[19], 0xb1)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[9], s[4], 0x9d)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[9], s[20], 0x9c)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[9], s[21], 0x9e)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[9], s[22], 0x9f)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[9], s[23], 0xac)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[9], s[24], 0xad)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[10], s[25], 0xac)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[10], s[26], 0xbc)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[10], s[27], 0xbd)) { return 0; }
	for (i = 0x80; i <= 0xa5; i++) {
		if (!fsm_addedge_literal(fsm, s[11], s[1], i)) { return 0; }
	}
	for (i = 0xac; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[11], s[1], i)) { return 0; }
	}
	for (i = 0x80; i <= 0x9c; i++) {
		if (!fsm_addedge_literal(fsm, s[12], s[1], i)) { return 0; }
	}
	for (i = 0xa2; i <= 0xa5; i++) {
		if (!fsm_addedge_literal(fsm, s[12], s[1], i)) { return 0; }
	}
	for (i = 0xab; i <= 0xb7; i++) {
		if (!fsm_addedge_literal(fsm, s[12], s[1], i)) { return 0; }
	}
	for (i = 0xb9; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[12], s[1], i)) { return 0; }
	}
	for (i = 0x80; i <= 0xbe; i++) {
		if (!fsm_addedge_literal(fsm, s[13], s[1], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[14], s[1], 0xb1)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[14], s[1], 0xbf)) { return 0; }
	for (i = 0x90; i <= 0x9c; i++) {
		if (!fsm_addedge_literal(fsm, s[15], s[1], i)) { return 0; }
	}
	for (i = 0xaa; i <= 0xab; i++) {
		if (!fsm_addedge_literal(fsm, s[16], s[1], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[16], s[1], 0xb2)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[17], s[1], 0x8e)) { return 0; }
	for (i = 0xa0; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[17], s[1], i)) { return 0; }
	}
	for (i = 0x80; i <= 0x88; i++) {
		if (!fsm_addedge_literal(fsm, s[18], s[1], i)) { return 0; }
	}
	for (i = 0xa0; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[19], s[1], i)) { return 0; }
	}
	for (i = 0xa2; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[20], s[1], i)) { return 0; }
	}
	for (i = 0x80; i <= 0x87; i++) {
		if (!fsm_addedge_literal(fsm, s[21], s[1], i)) { return 0; }
	}
	for (i = 0x8b; i <= 0xae; i++) {
		if (!fsm_addedge_literal(fsm, s[21], s[1], i)) { return 0; }
	}
	for (i = 0xb0; i <= 0xb7; i++) {
		if (!fsm_addedge_literal(fsm, s[21], s[1], i)) { return 0; }
	}
	for (i = 0xb7; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[22], s[1], i)) { return 0; }
	}
	for (i = 0xb0; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[23], s[1], i)) { return 0; }
	}
	for (i = 0x80; i <= 0x9a; i++) {
		if (!fsm_addedge_literal(fsm, s[24], s[1], i)) { return 0; }
	}
	for (i = 0x9c; i <= 0xa4; i++) {
		if (!fsm_addedge_literal(fsm, s[24], s[1], i)) { return 0; }
	}
	for (i = 0x80; i <= 0x86; i++) {
		if (!fsm_addedge_literal(fsm, s[25], s[1], i)) { return 0; }
	}
	for (i = 0xa1; i <= 0xba; i++) {
		if (!fsm_addedge_literal(fsm, s[26], s[1], i)) { return 0; }
	}
	for (i = 0x81; i <= 0x9a; i++) {
		if (!fsm_addedge_literal(fsm, s[27], s[1], i)) { return 0; }
	}


	return 1;
}

