/* Generated by libfsm */

#include LF_HEADER

#include <stddef.h>

#include <fsm/fsm.h>

struct fsm *
utf8_P_fsm(const struct fsm_options *opt)
{
	struct fsm *fsm;
	size_t i;

	struct fsm_state *s[113] = { 0 };

	fsm = fsm_new(opt);
	if (fsm == NULL) {
		return NULL;
	}

	for (i = 0; i < 113; i++) {
		s[i] = fsm_addstate(fsm);
		if (s[i] == NULL) {
			goto error;
		}
	}

	if (!fsm_addedge_literal(fsm, s[0], s[1], 0xc2)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[2], 0xcd)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[3], 0xce)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[4], 0xd5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[5], 0xd6)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[6], 0xd7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[7], 0xd8)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[8], 0xd9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[9], 0xdb)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[10], 0xdc)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[11], 0xdf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[12], 0xe0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[13], 0xe1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[14], 0xe2)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[15], 0xe3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[16], 0xea)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[17], 0xef)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[18], 0xf0)) { goto error; }
	for (i = 0x21; i <= 0x23; i++) {
		if (!fsm_addedge_literal(fsm, s[0], s[19], i)) { goto error; }
	}
	for (i = 0x25; i <= 0x2a; i++) {
		if (!fsm_addedge_literal(fsm, s[0], s[19], i)) { goto error; }
	}
	for (i = 0x2c; i <= 0x2f; i++) {
		if (!fsm_addedge_literal(fsm, s[0], s[19], i)) { goto error; }
	}
	for (i = 0x3a; i <= 0x3b; i++) {
		if (!fsm_addedge_literal(fsm, s[0], s[19], i)) { goto error; }
	}
	for (i = 0x3f; i <= 0x40; i++) {
		if (!fsm_addedge_literal(fsm, s[0], s[19], i)) { goto error; }
	}
	for (i = 0x5b; i <= 0x5d; i++) {
		if (!fsm_addedge_literal(fsm, s[0], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[0], s[19], '_')) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[19], '{')) { goto error; }
	if (!fsm_addedge_literal(fsm, s[0], s[19], '}')) { goto error; }
	if (!fsm_addedge_literal(fsm, s[1], s[19], 0xa1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[1], s[19], 0xa7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[1], s[19], 0xab)) { goto error; }
	for (i = 0xb6; i <= 0xb7; i++) {
		if (!fsm_addedge_literal(fsm, s[1], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[1], s[19], 0xbb)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[1], s[19], 0xbf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[2], s[19], 0xbe)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[3], s[19], 0x87)) { goto error; }
	for (i = 0x9a; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[4], s[19], i)) { goto error; }
	}
	for (i = 0x89; i <= 0x8a; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[5], s[19], 0xbe)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[19], 0x80)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[19], 0x83)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[6], s[19], 0x86)) { goto error; }
	for (i = 0xb3; i <= 0xb4; i++) {
		if (!fsm_addedge_literal(fsm, s[6], s[19], i)) { goto error; }
	}
	for (i = 0x89; i <= 0x8a; i++) {
		if (!fsm_addedge_literal(fsm, s[7], s[19], i)) { goto error; }
	}
	for (i = 0x8c; i <= 0x8d; i++) {
		if (!fsm_addedge_literal(fsm, s[7], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[7], s[19], 0x9b)) { goto error; }
	for (i = 0x9e; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[7], s[19], i)) { goto error; }
	}
	for (i = 0xaa; i <= 0xad; i++) {
		if (!fsm_addedge_literal(fsm, s[8], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[9], s[19], 0x94)) { goto error; }
	for (i = 0x80; i <= 0x8d; i++) {
		if (!fsm_addedge_literal(fsm, s[10], s[19], i)) { goto error; }
	}
	for (i = 0xb7; i <= 0xb9; i++) {
		if (!fsm_addedge_literal(fsm, s[11], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[12], s[35], 0xa0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[12], s[36], 0xa1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[12], s[37], 0xa5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[12], s[38], 0xa7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[12], s[39], 0xab)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[12], s[40], 0xb7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[12], s[41], 0xb9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[12], s[42], 0xbc)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[12], s[43], 0xbe)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[12], s[44], 0xbf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[22], 0x83)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[23], 0xb1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[45], 0x81)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[46], 0x8d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[47], 0x90)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[48], 0x99)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[49], 0x9a)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[50], 0x9b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[51], 0x9c)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[52], 0x9f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[53], 0xa0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[54], 0xa5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[55], 0xa8)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[56], 0xaa)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[57], 0xad)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[58], 0xaf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[59], 0xb0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[13], s[60], 0xb3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[14], s[39], 0xb5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[14], s[102], 0x80)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[14], s[103], 0x81)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[14], s[104], 0x82)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[14], s[105], 0x8c)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[14], s[106], 0x9d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[14], s[107], 0x9f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[14], s[108], 0xa6)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[14], s[109], 0xa7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[14], s[110], 0xb3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[14], s[111], 0xb8)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[14], s[112], 0xb9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[15], s[20], 0x80)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[15], s[21], 0x82)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[15], s[22], 0x83)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[23], 0x93)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[24], 0x98)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[25], 0x99)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[26], 0x9b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[27], 0xa1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[28], 0xa3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[29], 0xa4)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[30], 0xa5)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[31], 0xa7)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[32], 0xa9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[33], 0xab)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[16], s[34], 0xaf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[23], 0xb4)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[61], 0xb8)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[62], 0xb9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[63], 0xbc)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[17], s[64], 0xbd)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[65], 0x90)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[66], 0x91)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[67], 0x92)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[68], 0x96)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[69], 0x9b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[70], 0x9d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[18], s[71], 0x9e)) { goto error; }
	for (i = 0x81; i <= 0x83; i++) {
		if (!fsm_addedge_literal(fsm, s[20], s[19], i)) { goto error; }
	}
	for (i = 0x88; i <= 0x91; i++) {
		if (!fsm_addedge_literal(fsm, s[20], s[19], i)) { goto error; }
	}
	for (i = 0x94; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[20], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[20], s[19], 0xb0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[20], s[19], 0xbd)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[21], s[19], 0xa0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[22], s[19], 0xbb)) { goto error; }
	for (i = 0xbe; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[23], s[19], i)) { goto error; }
	}
	for (i = 0x8d; i <= 0x8f; i++) {
		if (!fsm_addedge_literal(fsm, s[24], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[25], s[19], 0xb3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[25], s[19], 0xbe)) { goto error; }
	for (i = 0xb2; i <= 0xb7; i++) {
		if (!fsm_addedge_literal(fsm, s[26], s[19], i)) { goto error; }
	}
	for (i = 0xb4; i <= 0xb7; i++) {
		if (!fsm_addedge_literal(fsm, s[27], s[19], i)) { goto error; }
	}
	for (i = 0x8e; i <= 0x8f; i++) {
		if (!fsm_addedge_literal(fsm, s[28], s[19], i)) { goto error; }
	}
	for (i = 0xb8; i <= 0xba; i++) {
		if (!fsm_addedge_literal(fsm, s[28], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[28], s[19], 0xbc)) { goto error; }
	for (i = 0xae; i <= 0xaf; i++) {
		if (!fsm_addedge_literal(fsm, s[29], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[30], s[19], 0x9f)) { goto error; }
	for (i = 0x81; i <= 0x8d; i++) {
		if (!fsm_addedge_literal(fsm, s[31], s[19], i)) { goto error; }
	}
	for (i = 0x9e; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[31], s[19], i)) { goto error; }
	}
	for (i = 0x9c; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[32], s[19], i)) { goto error; }
	}
	for (i = 0x9e; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[33], s[19], i)) { goto error; }
	}
	for (i = 0xb0; i <= 0xb1; i++) {
		if (!fsm_addedge_literal(fsm, s[33], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[34], s[19], 0xab)) { goto error; }
	for (i = 0xb0; i <= 0xbe; i++) {
		if (!fsm_addedge_literal(fsm, s[35], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[36], s[19], 0x9e)) { goto error; }
	for (i = 0xa4; i <= 0xa5; i++) {
		if (!fsm_addedge_literal(fsm, s[37], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[37], s[19], 0xb0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[38], s[19], 0xbd)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[39], s[19], 0xb0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[40], s[19], 0xb4)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[41], s[19], 0x8f)) { goto error; }
	for (i = 0x9a; i <= 0x9b; i++) {
		if (!fsm_addedge_literal(fsm, s[41], s[19], i)) { goto error; }
	}
	for (i = 0x84; i <= 0x92; i++) {
		if (!fsm_addedge_literal(fsm, s[42], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[42], s[19], 0x94)) { goto error; }
	for (i = 0xba; i <= 0xbd; i++) {
		if (!fsm_addedge_literal(fsm, s[42], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[43], s[19], 0x85)) { goto error; }
	for (i = 0x90; i <= 0x94; i++) {
		if (!fsm_addedge_literal(fsm, s[44], s[19], i)) { goto error; }
	}
	for (i = 0x99; i <= 0x9a; i++) {
		if (!fsm_addedge_literal(fsm, s[44], s[19], i)) { goto error; }
	}
	for (i = 0x8a; i <= 0x8f; i++) {
		if (!fsm_addedge_literal(fsm, s[45], s[19], i)) { goto error; }
	}
	for (i = 0xa0; i <= 0xa8; i++) {
		if (!fsm_addedge_literal(fsm, s[46], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[47], s[19], 0x80)) { goto error; }
	for (i = 0xad; i <= 0xae; i++) {
		if (!fsm_addedge_literal(fsm, s[48], s[19], i)) { goto error; }
	}
	for (i = 0x9b; i <= 0x9c; i++) {
		if (!fsm_addedge_literal(fsm, s[49], s[19], i)) { goto error; }
	}
	for (i = 0xab; i <= 0xad; i++) {
		if (!fsm_addedge_literal(fsm, s[50], s[19], i)) { goto error; }
	}
	for (i = 0xb5; i <= 0xb6; i++) {
		if (!fsm_addedge_literal(fsm, s[51], s[19], i)) { goto error; }
	}
	for (i = 0x94; i <= 0x96; i++) {
		if (!fsm_addedge_literal(fsm, s[52], s[19], i)) { goto error; }
	}
	for (i = 0x98; i <= 0x9a; i++) {
		if (!fsm_addedge_literal(fsm, s[52], s[19], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x8a; i++) {
		if (!fsm_addedge_literal(fsm, s[53], s[19], i)) { goto error; }
	}
	for (i = 0x84; i <= 0x85; i++) {
		if (!fsm_addedge_literal(fsm, s[54], s[19], i)) { goto error; }
	}
	for (i = 0x9e; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[55], s[19], i)) { goto error; }
	}
	for (i = 0xa0; i <= 0xa6; i++) {
		if (!fsm_addedge_literal(fsm, s[56], s[19], i)) { goto error; }
	}
	for (i = 0xa8; i <= 0xad; i++) {
		if (!fsm_addedge_literal(fsm, s[56], s[19], i)) { goto error; }
	}
	for (i = 0x9a; i <= 0xa0; i++) {
		if (!fsm_addedge_literal(fsm, s[57], s[19], i)) { goto error; }
	}
	for (i = 0xbc; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[58], s[19], i)) { goto error; }
	}
	for (i = 0xbb; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[59], s[19], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x87; i++) {
		if (!fsm_addedge_literal(fsm, s[60], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[60], s[19], 0x93)) { goto error; }
	for (i = 0x90; i <= 0x99; i++) {
		if (!fsm_addedge_literal(fsm, s[61], s[19], i)) { goto error; }
	}
	for (i = 0xb0; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[61], s[19], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x92; i++) {
		if (!fsm_addedge_literal(fsm, s[62], s[19], i)) { goto error; }
	}
	for (i = 0x94; i <= 0xa1; i++) {
		if (!fsm_addedge_literal(fsm, s[62], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[62], s[19], 0xa3)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[62], s[19], 0xa8)) { goto error; }
	for (i = 0xaa; i <= 0xab; i++) {
		if (!fsm_addedge_literal(fsm, s[62], s[19], i)) { goto error; }
	}
	for (i = 0x81; i <= 0x83; i++) {
		if (!fsm_addedge_literal(fsm, s[63], s[19], i)) { goto error; }
	}
	for (i = 0x85; i <= 0x8a; i++) {
		if (!fsm_addedge_literal(fsm, s[63], s[19], i)) { goto error; }
	}
	for (i = 0x8c; i <= 0x8f; i++) {
		if (!fsm_addedge_literal(fsm, s[63], s[19], i)) { goto error; }
	}
	for (i = 0x9a; i <= 0x9b; i++) {
		if (!fsm_addedge_literal(fsm, s[63], s[19], i)) { goto error; }
	}
	for (i = 0x9f; i <= 0xa0; i++) {
		if (!fsm_addedge_literal(fsm, s[63], s[19], i)) { goto error; }
	}
	for (i = 0xbb; i <= 0xbd; i++) {
		if (!fsm_addedge_literal(fsm, s[63], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[63], s[19], 0xbf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[64], s[19], 0x9b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[64], s[19], 0x9d)) { goto error; }
	for (i = 0x9f; i <= 0xa5; i++) {
		if (!fsm_addedge_literal(fsm, s[64], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[65], s[30], 0x8e)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[65], s[77], 0x84)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[65], s[78], 0x8f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[65], s[79], 0x95)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[65], s[80], 0xa1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[65], s[81], 0xa4)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[65], s[82], 0xa9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[65], s[83], 0xab)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[65], s[84], 0xac)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[65], s[85], 0xae)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[66], s[86], 0x81)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[66], s[87], 0x82)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[66], s[88], 0x83)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[66], s[89], 0x85)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[66], s[90], 0x87)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[66], s[91], 0x88)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[66], s[92], 0x8a)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[66], s[93], 0x91)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[66], s[94], 0x93)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[66], s[95], 0x97)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[66], s[96], 0x99)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[66], s[97], 0x9c)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[66], s[98], 0xa8)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[66], s[99], 0xa9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[66], s[100], 0xaa)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[66], s[101], 0xb1)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[67], s[73], 0x91)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[68], s[29], 0xa9)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[68], s[74], 0xab)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[68], s[75], 0xac)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[68], s[76], 0xad)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[69], s[30], 0xb2)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[70], s[72], 0xaa)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[71], s[55], 0xa5)) { goto error; }
	for (i = 0x87; i <= 0x8b; i++) {
		if (!fsm_addedge_literal(fsm, s[72], s[19], i)) { goto error; }
	}
	for (i = 0xb0; i <= 0xb4; i++) {
		if (!fsm_addedge_literal(fsm, s[73], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[74], s[19], 0xb5)) { goto error; }
	for (i = 0xb7; i <= 0xbb; i++) {
		if (!fsm_addedge_literal(fsm, s[75], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[76], s[19], 0x84)) { goto error; }
	for (i = 0x80; i <= 0x82; i++) {
		if (!fsm_addedge_literal(fsm, s[77], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[78], s[19], 0x90)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[79], s[19], 0xaf)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[80], s[19], 0x97)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[81], s[19], 0x9f)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[81], s[19], 0xbf)) { goto error; }
	for (i = 0x90; i <= 0x98; i++) {
		if (!fsm_addedge_literal(fsm, s[82], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[82], s[19], 0xbf)) { goto error; }
	for (i = 0xb0; i <= 0xb6; i++) {
		if (!fsm_addedge_literal(fsm, s[83], s[19], i)) { goto error; }
	}
	for (i = 0xb9; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[84], s[19], i)) { goto error; }
	}
	for (i = 0x99; i <= 0x9c; i++) {
		if (!fsm_addedge_literal(fsm, s[85], s[19], i)) { goto error; }
	}
	for (i = 0x87; i <= 0x8d; i++) {
		if (!fsm_addedge_literal(fsm, s[86], s[19], i)) { goto error; }
	}
	for (i = 0xbb; i <= 0xbc; i++) {
		if (!fsm_addedge_literal(fsm, s[87], s[19], i)) { goto error; }
	}
	for (i = 0xbe; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[87], s[19], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x81; i++) {
		if (!fsm_addedge_literal(fsm, s[88], s[19], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x83; i++) {
		if (!fsm_addedge_literal(fsm, s[89], s[19], i)) { goto error; }
	}
	for (i = 0xb4; i <= 0xb5; i++) {
		if (!fsm_addedge_literal(fsm, s[89], s[19], i)) { goto error; }
	}
	for (i = 0x85; i <= 0x89; i++) {
		if (!fsm_addedge_literal(fsm, s[90], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[90], s[19], 0x8d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[90], s[19], 0x9b)) { goto error; }
	for (i = 0x9d; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[90], s[19], i)) { goto error; }
	}
	for (i = 0xb8; i <= 0xbd; i++) {
		if (!fsm_addedge_literal(fsm, s[91], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[92], s[19], 0xa9)) { goto error; }
	for (i = 0x8b; i <= 0x8f; i++) {
		if (!fsm_addedge_literal(fsm, s[93], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[93], s[19], 0x9b)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[93], s[19], 0x9d)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[94], s[19], 0x86)) { goto error; }
	for (i = 0x81; i <= 0x97; i++) {
		if (!fsm_addedge_literal(fsm, s[95], s[19], i)) { goto error; }
	}
	for (i = 0x81; i <= 0x83; i++) {
		if (!fsm_addedge_literal(fsm, s[96], s[19], i)) { goto error; }
	}
	for (i = 0xa0; i <= 0xac; i++) {
		if (!fsm_addedge_literal(fsm, s[96], s[19], i)) { goto error; }
	}
	for (i = 0xbc; i <= 0xbe; i++) {
		if (!fsm_addedge_literal(fsm, s[97], s[19], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[98], s[19], 0xbf)) { goto error; }
	for (i = 0x80; i <= 0x86; i++) {
		if (!fsm_addedge_literal(fsm, s[99], s[19], i)) { goto error; }
	}
	for (i = 0x9a; i <= 0x9c; i++) {
		if (!fsm_addedge_literal(fsm, s[100], s[19], i)) { goto error; }
	}
	for (i = 0x9e; i <= 0xa2; i++) {
		if (!fsm_addedge_literal(fsm, s[100], s[19], i)) { goto error; }
	}
	for (i = 0x81; i <= 0x85; i++) {
		if (!fsm_addedge_literal(fsm, s[101], s[19], i)) { goto error; }
	}
	for (i = 0xb0; i <= 0xb1; i++) {
		if (!fsm_addedge_literal(fsm, s[101], s[19], i)) { goto error; }
	}
	for (i = 0x90; i <= 0xa7; i++) {
		if (!fsm_addedge_literal(fsm, s[102], s[19], i)) { goto error; }
	}
	for (i = 0xb0; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[102], s[19], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x83; i++) {
		if (!fsm_addedge_literal(fsm, s[103], s[19], i)) { goto error; }
	}
	for (i = 0x85; i <= 0x91; i++) {
		if (!fsm_addedge_literal(fsm, s[103], s[19], i)) { goto error; }
	}
	for (i = 0x93; i <= 0x9e; i++) {
		if (!fsm_addedge_literal(fsm, s[103], s[19], i)) { goto error; }
	}
	for (i = 0xbd; i <= 0xbe; i++) {
		if (!fsm_addedge_literal(fsm, s[103], s[19], i)) { goto error; }
	}
	for (i = 0x8d; i <= 0x8e; i++) {
		if (!fsm_addedge_literal(fsm, s[104], s[19], i)) { goto error; }
	}
	for (i = 0x88; i <= 0x8b; i++) {
		if (!fsm_addedge_literal(fsm, s[105], s[19], i)) { goto error; }
	}
	for (i = 0xa9; i <= 0xaa; i++) {
		if (!fsm_addedge_literal(fsm, s[105], s[19], i)) { goto error; }
	}
	for (i = 0xa8; i <= 0xb5; i++) {
		if (!fsm_addedge_literal(fsm, s[106], s[19], i)) { goto error; }
	}
	for (i = 0x85; i <= 0x86; i++) {
		if (!fsm_addedge_literal(fsm, s[107], s[19], i)) { goto error; }
	}
	for (i = 0xa6; i <= 0xaf; i++) {
		if (!fsm_addedge_literal(fsm, s[107], s[19], i)) { goto error; }
	}
	for (i = 0x83; i <= 0x98; i++) {
		if (!fsm_addedge_literal(fsm, s[108], s[19], i)) { goto error; }
	}
	for (i = 0x98; i <= 0x9b; i++) {
		if (!fsm_addedge_literal(fsm, s[109], s[19], i)) { goto error; }
	}
	for (i = 0xbc; i <= 0xbd; i++) {
		if (!fsm_addedge_literal(fsm, s[109], s[19], i)) { goto error; }
	}
	for (i = 0xb9; i <= 0xbc; i++) {
		if (!fsm_addedge_literal(fsm, s[110], s[19], i)) { goto error; }
	}
	for (i = 0xbe; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[110], s[19], i)) { goto error; }
	}
	for (i = 0x80; i <= 0xae; i++) {
		if (!fsm_addedge_literal(fsm, s[111], s[19], i)) { goto error; }
	}
	for (i = 0xb0; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[111], s[19], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x89; i++) {
		if (!fsm_addedge_literal(fsm, s[112], s[19], i)) { goto error; }
	}

	fsm_setstart(fsm, s[0]);
	fsm_setend(fsm, s[19], 1);

	return fsm;

error:

	fsm_free(fsm);

	return NULL;
}

