/* Generated by libfsm */

#include LF_HEADER

#include <stddef.h>

#include <fsm/fsm.h>

struct fsm *
utf8_Linear_B_fsm(const struct fsm_options *opt)
{
	struct fsm *fsm;
	size_t i;

	struct fsm_state *s[8] = { 0 };

	fsm = fsm_new(opt);
	if (fsm == NULL) {
		return NULL;
	}

	for (i = 0; i < 8; i++) {
		s[i] = fsm_addstate(fsm);
		if (s[i] == NULL) {
			goto error;
		}
	}

	if (!fsm_addedge_literal(fsm, s[0], s[1], 0xf0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[1], s[2], 0x90)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[2], s[3], 0x80)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[2], s[4], 0x81)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[2], s[5], 0x82)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[2], s[6], 0x83)) { goto error; }
	for (i = 0x80; i <= 0x8b; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[7], i)) { goto error; }
	}
	for (i = 0x8d; i <= 0xa6; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[7], i)) { goto error; }
	}
	for (i = 0xa8; i <= 0xba; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[7], i)) { goto error; }
	}
	for (i = 0xbc; i <= 0xbd; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[7], i)) { goto error; }
	}
	if (!fsm_addedge_literal(fsm, s[3], s[7], 0xbf)) { goto error; }
	for (i = 0x80; i <= 0x8d; i++) {
		if (!fsm_addedge_literal(fsm, s[4], s[7], i)) { goto error; }
	}
	for (i = 0x90; i <= 0x9d; i++) {
		if (!fsm_addedge_literal(fsm, s[4], s[7], i)) { goto error; }
	}
	for (i = 0x80; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[7], i)) { goto error; }
	}
	for (i = 0x80; i <= 0xba; i++) {
		if (!fsm_addedge_literal(fsm, s[6], s[7], i)) { goto error; }
	}

	fsm_setstart(fsm, s[0]);
	fsm_setend(fsm, s[7], 1);

	return fsm;

error:

	fsm_free(fsm);

	return NULL;
}

