/* Generated by libfsm */

#include LF_HEADER

#include <stddef.h>

#include <fsm/fsm.h>

int
utf8_Cyrillic_fsm(struct fsm *fsm, fsm_state_t x, fsm_state_t y)
{
	fsm_state_t s[15];
	size_t i;

	for (i = 0; i < 15; i++) {
		if (i == 0) {
			s[0] = x;
			continue;
		}

		if (i == 11) {
			s[11] = y;
			continue;
		}

		if (!fsm_addstate(fsm, &s[i])) {
			return 0;
		}
	}

	for (i = 0xd0; i <= 0xd1; i++) {
		if (!fsm_addedge_literal(fsm, s[0], s[1], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[0], s[1], 0xd3)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[0], s[2], 0xd2)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[0], s[3], 0xd4)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[0], s[4], 0xe1)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[0], s[5], 0xe2)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[0], s[6], 0xea)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[0], s[7], 0xef)) { return 0; }
	for (i = 0x80; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[1], s[11], i)) { return 0; }
	}
	for (i = 0x80; i <= 0x84; i++) {
		if (!fsm_addedge_literal(fsm, s[2], s[11], i)) { return 0; }
	}
	for (i = 0x87; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[2], s[11], i)) { return 0; }
	}
	for (i = 0x80; i <= 0xaf; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[11], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[4], s[8], 0xb2)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[4], s[9], 0xb4)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[4], s[10], 0xb5)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[5], s[14], 0xb7)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[6], s[1], 0x99)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[6], s[12], 0x9a)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[7], s[13], 0xb8)) { return 0; }
	for (i = 0x80; i <= 0x88; i++) {
		if (!fsm_addedge_literal(fsm, s[8], s[11], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[9], s[11], 0xab)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[10], s[11], 0xb8)) { return 0; }
	for (i = 0x80; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[12], s[11], i)) { return 0; }
	}
	for (i = 0xae; i <= 0xaf; i++) {
		if (!fsm_addedge_literal(fsm, s[13], s[11], i)) { return 0; }
	}
	for (i = 0xa0; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[14], s[11], i)) { return 0; }
	}

	return 1;
}

