/* Generated by libfsm */

#include LF_HEADER

#include <stddef.h>

#include <fsm/fsm.h>

struct fsm *
utf8_Malayalam_fsm(const struct fsm_options *opt)
{
	struct fsm *fsm;
	size_t i;

	struct fsm_state *s[5] = { 0 };

	fsm = fsm_new(opt);
	if (fsm == NULL) {
		return NULL;
	}

	for (i = 0; i < 5; i++) {
		s[i] = fsm_addstate(fsm);
		if (s[i] == NULL) {
			goto error;
		}
	}

	if (!fsm_addedge_literal(fsm, s[0], s[1], 0xe0)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[1], s[2], 0xb4)) { goto error; }
	if (!fsm_addedge_literal(fsm, s[1], s[3], 0xb5)) { goto error; }
	for (i = 0x80; i <= 0x83; i++) {
		if (!fsm_addedge_literal(fsm, s[2], s[4], i)) { goto error; }
	}
	for (i = 0x85; i <= 0x8c; i++) {
		if (!fsm_addedge_literal(fsm, s[2], s[4], i)) { goto error; }
	}
	for (i = 0x8e; i <= 0x90; i++) {
		if (!fsm_addedge_literal(fsm, s[2], s[4], i)) { goto error; }
	}
	for (i = 0x92; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[2], s[4], i)) { goto error; }
	}
	for (i = 0x80; i <= 0x84; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[4], i)) { goto error; }
	}
	for (i = 0x86; i <= 0x88; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[4], i)) { goto error; }
	}
	for (i = 0x8a; i <= 0x8f; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[4], i)) { goto error; }
	}
	for (i = 0x94; i <= 0xa3; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[4], i)) { goto error; }
	}
	for (i = 0xa6; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[4], i)) { goto error; }
	}

	fsm_setstart(fsm, s[0]);
	fsm_setend(fsm, s[4], 1);

	return fsm;

error:

	fsm_free(fsm);

	return NULL;
}

