/* Generated by libfsm */

#include LF_HEADER

#include <assert.h>
#include <stddef.h>

#include <fsm/fsm.h>

int
utf8_Mongolian_fsm(struct fsm *fsm, struct fsm_state *x, struct fsm_state *y)
{
	struct fsm_state *s[9];
	size_t i;

	assert(x != NULL);
	assert(y != NULL);

	for (i = 0; i < 9; i++) {
		if (i == 0) {
			s[0] = x;
			continue;
		}

		if (i == 7) {
			s[7] = y;
			continue;
		}

		s[i] = fsm_addstate(fsm);
		if (s[i] == NULL) {
			return 0;
		}
	}

	if (!fsm_addedge_literal(fsm, s[0], s[1], 0xe1)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[0], s[2], 0xf0)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[1], s[4], 0xa0)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[1], s[5], 0xa1)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[1], s[6], 0xa2)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[2], s[3], 0x91)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[3], s[8], 0x99)) { return 0; }
	for (i = 0x80; i <= 0x81; i++) {
		if (!fsm_addedge_literal(fsm, s[4], s[7], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[4], s[7], 0x84)) { return 0; }
	for (i = 0x86; i <= 0x8e; i++) {
		if (!fsm_addedge_literal(fsm, s[4], s[7], i)) { return 0; }
	}
	for (i = 0x90; i <= 0x99; i++) {
		if (!fsm_addedge_literal(fsm, s[4], s[7], i)) { return 0; }
	}
	for (i = 0xa0; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[4], s[7], i)) { return 0; }
	}
	for (i = 0x80; i <= 0xb7; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[7], i)) { return 0; }
	}
	for (i = 0x80; i <= 0xaa; i++) {
		if (!fsm_addedge_literal(fsm, s[6], s[7], i)) { return 0; }
	}
	for (i = 0xa0; i <= 0xac; i++) {
		if (!fsm_addedge_literal(fsm, s[8], s[7], i)) { return 0; }
	}


	return 1;
}

