/* Generated by libfsm */

#include LF_HEADER

#include <assert.h>
#include <stddef.h>

#include <fsm/fsm.h>

int
utf8_No_fsm(struct fsm *fsm, struct fsm_state *x, struct fsm_state *y)
{
	struct fsm_state *s[66];
	size_t i;

	assert(x != NULL);
	assert(y != NULL);

	for (i = 0; i < 66; i++) {
		if (i == 0) {
			s[0] = x;
			continue;
		}

		if (i == 8) {
			s[8] = y;
			continue;
		}

		s[i] = fsm_addstate(fsm);
		if (s[i] == NULL) {
			return 0;
		}
	}

	if (!fsm_addedge_literal(fsm, s[0], s[1], 0xc2)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[0], s[2], 0xe0)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[0], s[3], 0xe1)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[0], s[4], 0xe2)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[0], s[5], 0xe3)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[0], s[6], 0xea)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[0], s[7], 0xf0)) { return 0; }
	for (i = 0xb2; i <= 0xb3; i++) {
		if (!fsm_addedge_literal(fsm, s[1], s[8], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[1], s[8], 0xb9)) { return 0; }
	for (i = 0xbc; i <= 0xbe; i++) {
		if (!fsm_addedge_literal(fsm, s[1], s[8], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[2], s[9], 0xa7)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[2], s[10], 0xad)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[2], s[11], 0xaf)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[2], s[12], 0xb1)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[2], s[13], 0xb5)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[2], s[14], 0xbc)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[3], s[26], 0x8d)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[3], s[27], 0x9f)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[3], s[28], 0xa7)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[4], s[16], 0x81)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[4], s[17], 0x82)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[4], s[18], 0x85)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[4], s[19], 0x86)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[4], s[20], 0x91)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[4], s[21], 0x92)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[4], s[22], 0x93)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[4], s[23], 0x9d)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[4], s[24], 0x9e)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[4], s[25], 0xb3)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[5], s[35], 0x86)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[5], s[36], 0x88)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[5], s[37], 0x89)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[5], s[38], 0x8a)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[6], s[15], 0xa0)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[7], s[29], 0x90)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[7], s[30], 0x91)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[7], s[31], 0x96)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[7], s[32], 0x9d)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[7], s[33], 0x9e)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[7], s[34], 0x9f)) { return 0; }
	for (i = 0xb4; i <= 0xb9; i++) {
		if (!fsm_addedge_literal(fsm, s[9], s[8], i)) { return 0; }
	}
	for (i = 0xb2; i <= 0xb7; i++) {
		if (!fsm_addedge_literal(fsm, s[10], s[8], i)) { return 0; }
	}
	for (i = 0xb0; i <= 0xb2; i++) {
		if (!fsm_addedge_literal(fsm, s[11], s[8], i)) { return 0; }
	}
	for (i = 0xb8; i <= 0xbe; i++) {
		if (!fsm_addedge_literal(fsm, s[12], s[8], i)) { return 0; }
	}
	for (i = 0x98; i <= 0x9e; i++) {
		if (!fsm_addedge_literal(fsm, s[13], s[8], i)) { return 0; }
	}
	for (i = 0xb0; i <= 0xb8; i++) {
		if (!fsm_addedge_literal(fsm, s[13], s[8], i)) { return 0; }
	}
	for (i = 0xaa; i <= 0xb3; i++) {
		if (!fsm_addedge_literal(fsm, s[14], s[8], i)) { return 0; }
	}
	for (i = 0xb0; i <= 0xb5; i++) {
		if (!fsm_addedge_literal(fsm, s[15], s[8], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[16], s[8], 0xb0)) { return 0; }
	for (i = 0xb4; i <= 0xb9; i++) {
		if (!fsm_addedge_literal(fsm, s[16], s[8], i)) { return 0; }
	}
	for (i = 0x80; i <= 0x89; i++) {
		if (!fsm_addedge_literal(fsm, s[17], s[8], i)) { return 0; }
	}
	for (i = 0x90; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[18], s[8], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[19], s[8], 0x89)) { return 0; }
	for (i = 0xa0; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[20], s[8], i)) { return 0; }
	}
	for (i = 0x80; i <= 0x9b; i++) {
		if (!fsm_addedge_literal(fsm, s[21], s[8], i)) { return 0; }
	}
	for (i = 0xaa; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[22], s[8], i)) { return 0; }
	}
	for (i = 0xb6; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[23], s[8], i)) { return 0; }
	}
	for (i = 0x80; i <= 0x93; i++) {
		if (!fsm_addedge_literal(fsm, s[24], s[8], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[25], s[8], 0xbd)) { return 0; }
	for (i = 0xa9; i <= 0xbc; i++) {
		if (!fsm_addedge_literal(fsm, s[26], s[8], i)) { return 0; }
	}
	for (i = 0xb0; i <= 0xb9; i++) {
		if (!fsm_addedge_literal(fsm, s[27], s[8], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[28], s[8], 0x9a)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[29], s[48], 0x84)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[29], s[49], 0x85)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[29], s[50], 0x86)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[29], s[51], 0x8b)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[29], s[52], 0x8c)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[29], s[53], 0xa1)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[29], s[54], 0xa2)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[29], s[55], 0xa3)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[29], s[56], 0xa4)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[29], s[57], 0xa6)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[29], s[58], 0xa7)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[29], s[59], 0xa9)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[29], s[60], 0xaa)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[29], s[61], 0xab)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[29], s[62], 0xad)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[29], s[63], 0xae)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[29], s[64], 0xb3)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[29], s[65], 0xb9)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[30], s[43], 0x81)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[30], s[44], 0x87)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[30], s[45], 0x9c)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[30], s[46], 0xa3)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[30], s[47], 0xb1)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[31], s[40], 0xad)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[32], s[41], 0x8d)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[33], s[42], 0xa3)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[34], s[39], 0x84)) { return 0; }
	for (i = 0x92; i <= 0x95; i++) {
		if (!fsm_addedge_literal(fsm, s[35], s[8], i)) { return 0; }
	}
	for (i = 0xa0; i <= 0xa9; i++) {
		if (!fsm_addedge_literal(fsm, s[36], s[8], i)) { return 0; }
	}
	for (i = 0x88; i <= 0x8f; i++) {
		if (!fsm_addedge_literal(fsm, s[37], s[8], i)) { return 0; }
	}
	for (i = 0x91; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[37], s[8], i)) { return 0; }
	}
	for (i = 0x80; i <= 0x89; i++) {
		if (!fsm_addedge_literal(fsm, s[38], s[8], i)) { return 0; }
	}
	for (i = 0xb1; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[38], s[8], i)) { return 0; }
	}
	for (i = 0x80; i <= 0x8c; i++) {
		if (!fsm_addedge_literal(fsm, s[39], s[8], i)) { return 0; }
	}
	for (i = 0x9b; i <= 0xa1; i++) {
		if (!fsm_addedge_literal(fsm, s[40], s[8], i)) { return 0; }
	}
	for (i = 0xa0; i <= 0xb1; i++) {
		if (!fsm_addedge_literal(fsm, s[41], s[8], i)) { return 0; }
	}
	for (i = 0x87; i <= 0x8f; i++) {
		if (!fsm_addedge_literal(fsm, s[42], s[8], i)) { return 0; }
	}
	for (i = 0x92; i <= 0xa5; i++) {
		if (!fsm_addedge_literal(fsm, s[43], s[8], i)) { return 0; }
	}
	for (i = 0xa1; i <= 0xb4; i++) {
		if (!fsm_addedge_literal(fsm, s[44], s[8], i)) { return 0; }
	}
	for (i = 0xba; i <= 0xbb; i++) {
		if (!fsm_addedge_literal(fsm, s[45], s[8], i)) { return 0; }
	}
	for (i = 0xaa; i <= 0xb2; i++) {
		if (!fsm_addedge_literal(fsm, s[46], s[8], i)) { return 0; }
	}
	for (i = 0x9a; i <= 0xac; i++) {
		if (!fsm_addedge_literal(fsm, s[47], s[8], i)) { return 0; }
	}
	for (i = 0x87; i <= 0xb3; i++) {
		if (!fsm_addedge_literal(fsm, s[48], s[8], i)) { return 0; }
	}
	for (i = 0xb5; i <= 0xb8; i++) {
		if (!fsm_addedge_literal(fsm, s[49], s[8], i)) { return 0; }
	}
	for (i = 0x8a; i <= 0x8b; i++) {
		if (!fsm_addedge_literal(fsm, s[50], s[8], i)) { return 0; }
	}
	for (i = 0xa1; i <= 0xbb; i++) {
		if (!fsm_addedge_literal(fsm, s[51], s[8], i)) { return 0; }
	}
	for (i = 0xa0; i <= 0xa3; i++) {
		if (!fsm_addedge_literal(fsm, s[52], s[8], i)) { return 0; }
	}
	for (i = 0x98; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[53], s[8], i)) { return 0; }
	}
	for (i = 0xb9; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[53], s[8], i)) { return 0; }
	}
	for (i = 0xa7; i <= 0xaf; i++) {
		if (!fsm_addedge_literal(fsm, s[54], s[8], i)) { return 0; }
	}
	for (i = 0xbb; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[55], s[8], i)) { return 0; }
	}
	for (i = 0x96; i <= 0x9b; i++) {
		if (!fsm_addedge_literal(fsm, s[56], s[8], i)) { return 0; }
	}
	for (i = 0xbc; i <= 0xbd; i++) {
		if (!fsm_addedge_literal(fsm, s[57], s[8], i)) { return 0; }
	}
	for (i = 0x80; i <= 0x8f; i++) {
		if (!fsm_addedge_literal(fsm, s[58], s[8], i)) { return 0; }
	}
	for (i = 0x92; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[58], s[8], i)) { return 0; }
	}
	for (i = 0x80; i <= 0x87; i++) {
		if (!fsm_addedge_literal(fsm, s[59], s[8], i)) { return 0; }
	}
	for (i = 0xbd; i <= 0xbe; i++) {
		if (!fsm_addedge_literal(fsm, s[59], s[8], i)) { return 0; }
	}
	for (i = 0x9d; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[60], s[8], i)) { return 0; }
	}
	for (i = 0xab; i <= 0xaf; i++) {
		if (!fsm_addedge_literal(fsm, s[61], s[8], i)) { return 0; }
	}
	for (i = 0x98; i <= 0x9f; i++) {
		if (!fsm_addedge_literal(fsm, s[62], s[8], i)) { return 0; }
	}
	for (i = 0xb8; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[62], s[8], i)) { return 0; }
	}
	for (i = 0xa9; i <= 0xaf; i++) {
		if (!fsm_addedge_literal(fsm, s[63], s[8], i)) { return 0; }
	}
	for (i = 0xba; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[64], s[8], i)) { return 0; }
	}
	for (i = 0xa0; i <= 0xbe; i++) {
		if (!fsm_addedge_literal(fsm, s[65], s[8], i)) { return 0; }
	}


	return 1;
}

