/* Generated by libfsm */

#include LF_HEADER

#include <stddef.h>

#include <fsm/fsm.h>

int
utf8_private_fsm(struct fsm *fsm, fsm_state_t x, fsm_state_t y)
{
	fsm_state_t s[8];
	size_t i;

	for (i = 0; i < 8; i++) {
		if (i == 0) {
			s[0] = x;
			continue;
		}

		if (i == 7) {
			s[7] = y;
			continue;
		}

		if (!fsm_addstate(fsm, &s[i])) {
			return 0;
		}
	}

	if (!fsm_addedge_literal(fsm, s[0], s[1], 0xf3)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[0], s[2], 0xf4)) { return 0; }
	for (i = 0xb0; i <= 0xbe; i++) {
		if (!fsm_addedge_literal(fsm, s[1], s[3], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[1], s[4], 0xbf)) { return 0; }
	for (i = 0x80; i <= 0x8e; i++) {
		if (!fsm_addedge_literal(fsm, s[2], s[3], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[2], s[4], 0x8f)) { return 0; }
	for (i = 0x80; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[5], i)) { return 0; }
	}
	for (i = 0x80; i <= 0xbe; i++) {
		if (!fsm_addedge_literal(fsm, s[4], s[5], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[4], s[6], 0xbf)) { return 0; }
	for (i = 0x80; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[7], i)) { return 0; }
	}
	for (i = 0x80; i <= 0xbd; i++) {
		if (!fsm_addedge_literal(fsm, s[6], s[7], i)) { return 0; }
	}

	return 1;
}

