/* Generated by libfsm */

#include LF_HEADER

#include <stddef.h>

#include <fsm/fsm.h>

int
utf8_Linear_B_fsm(struct fsm *fsm, fsm_state_t x, fsm_state_t y)
{
	fsm_state_t s[8];
	size_t i;

	for (i = 0; i < 8; i++) {
		if (i == 0) {
			s[0] = x;
			continue;
		}

		if (i == 7) {
			s[7] = y;
			continue;
		}

		if (!fsm_addstate(fsm, &s[i])) {
			return 0;
		}
	}

	if (!fsm_addedge_literal(fsm, s[0], s[1], 0xf0)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[1], s[2], 0x90)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[2], s[3], 0x80)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[2], s[4], 0x81)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[2], s[5], 0x82)) { return 0; }
	if (!fsm_addedge_literal(fsm, s[2], s[6], 0x83)) { return 0; }
	for (i = 0x80; i <= 0x8b; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[7], i)) { return 0; }
	}
	for (i = 0x8d; i <= 0xa6; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[7], i)) { return 0; }
	}
	for (i = 0xa8; i <= 0xba; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[7], i)) { return 0; }
	}
	for (i = 0xbc; i <= 0xbd; i++) {
		if (!fsm_addedge_literal(fsm, s[3], s[7], i)) { return 0; }
	}
	if (!fsm_addedge_literal(fsm, s[3], s[7], 0xbf)) { return 0; }
	for (i = 0x80; i <= 0x8d; i++) {
		if (!fsm_addedge_literal(fsm, s[4], s[7], i)) { return 0; }
	}
	for (i = 0x90; i <= 0x9d; i++) {
		if (!fsm_addedge_literal(fsm, s[4], s[7], i)) { return 0; }
	}
	for (i = 0x80; i <= 0xbf; i++) {
		if (!fsm_addedge_literal(fsm, s[5], s[7], i)) { return 0; }
	}
	for (i = 0x80; i <= 0xba; i++) {
		if (!fsm_addedge_literal(fsm, s[6], s[7], i)) { return 0; }
	}

	return 1;
}

