/* Generated by lx */

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>

#include LX_HEADER

static enum lx_literal_token z0(struct lx_literal_lx *lx);

#if __STDC_VERSION__ >= 199901L
inline
#endif
static int
lx_getc(struct lx_literal_lx *lx)
{
	int c;

	assert(lx != NULL);
	assert(lx->lgetc != NULL);

	if (lx->c != EOF) {
		c = lx->c, lx->c = EOF;
	} else {
		c = lx->lgetc(lx);
		if (c == EOF) {
			return EOF;
		}
	}

	lx->end.byte++;
	lx->end.col++;

	if (c == '\n') {
		lx->end.line++;
		lx->end.col = 1;
	}

	return c;
}

#if __STDC_VERSION__ >= 199901L
inline
#endif
static void
lx_literal_ungetc(struct lx_literal_lx *lx, int c)
{
	assert(lx != NULL);
	assert(lx->c == EOF);

	lx->c = c;

	if (lx->pop != NULL) {
		lx->pop(lx);
	}

	lx->end.byte--;
	lx->end.col--;

	if (c == '\n') {
		lx->end.line--;
		lx->end.col = 0; /* XXX: lost information */
	}
}

int
lx_literal_dynpush(struct lx_literal_lx *lx, char c)
{
	struct lx_dynbuf *t;

	assert(lx != NULL);
	assert(c != EOF);

	t = lx->buf;

	assert(t != NULL);

	if (t->p == t->a + t->len) {
		size_t len;
		char *tmp;

		if (t->len == 0) {
			assert(LX_DYN_LOW > 0);
			len = LX_DYN_LOW;
		} else {
			len = t->len * LX_DYN_FACTOR;
			if (len < t->len) {
				errno = ERANGE;
				return -1;
			}
		}

		tmp = realloc(t->a, len);
		if (tmp == NULL) {
			return -1;
		}

		t->p   = tmp + (t->p - t->a);
		t->a   = tmp;
		t->len = len;
	}

	assert(t->p != NULL);
	assert(t->a != NULL);

	*t->p++ = c;

	return 0;
}

void
lx_literal_dynpop(struct lx_literal_lx *lx)
{
	struct lx_dynbuf *t;

	assert(lx != NULL);

	t = lx->buf;

	assert(t != NULL);
	assert(t->a != NULL);
	assert(t->p >= t->a);

	if (t->p == t->a) {
		return;
	}

	t->p--;
}

int
lx_literal_dynclear(struct lx_literal_lx *lx)
{
	struct lx_dynbuf *t;

	assert(lx != NULL);

	t = lx->buf;

	assert(t != NULL);

	if (t->len > LX_DYN_HIGH) {
		size_t len;
		char *tmp;

		len = t->len / LX_DYN_FACTOR;

		tmp = realloc(t->a, len);
		if (tmp == NULL) {
			return -1;
		}

		t->a   = tmp;
		t->len = len;
	}

	t->p = t->a;

	return 0;
}

void
lx_literal_dynfree(struct lx_literal_lx *lx)
{
	struct lx_dynbuf *t;

	assert(lx != NULL);

	t = lx->buf;

	assert(t != NULL);

	free(t->a);
}
static enum lx_literal_token
z0(struct lx_literal_lx *lx)
{
	int c;

	enum {
		S0, S1
	} state;

	assert(lx != NULL);

	if (lx->clear != NULL) {
		lx->clear(lx);
	}

	state = S0;

	lx->start = lx->end;

	while (c = lx_getc(lx), c != EOF) {
		if (lx->push != NULL) {
			if (-1 == lx->push(lx, c)) {
				return TOK_ERROR;
			}
		}

		switch (state) {
		case S0: /* start */
			switch (c) {
			case '\x00':
			case '\x01':
			case '\x02':
			case '\x03':
			case '\x04':
			case '\x05':
			case '\x06':
			case '\a':
			case '\b':
			case '\t':
			case '\n':
			case '\v':
			case '\f':
			case '\r':
			case '\x0e':
			case '\x0f':
			case '\x10':
			case '\x11':
			case '\x12':
			case '\x13':
			case '\x14':
			case '\x15':
			case '\x16':
			case '\x17':
			case '\x18':
			case '\x19':
			case '\x1a':
			case '\x1b':
			case '\x1c':
			case '\x1d':
			case '\x1e':
			case '\x1f':
			case ' ':
			case '!':
			case '"':
			case '#':
			case '$':
			case '%':
			case '&':
			case '\'':
			case '(':
			case ')':
			case '*':
			case '+':
			case ',':
			case '-':
			case '.':
			case '\x2f':
			case '0':
			case '1':
			case '2':
			case '3':
			case '4':
			case '5':
			case '6':
			case '7':
			case '8':
			case '9':
			case ':':
			case ';':
			case '<':
			case '=':
			case '>':
			case '?':
			case '@':
			case 'A':
			case 'B':
			case 'C':
			case 'D':
			case 'E':
			case 'F':
			case 'G':
			case 'H':
			case 'I':
			case 'J':
			case 'K':
			case 'L':
			case 'M':
			case 'N':
			case 'O':
			case 'P':
			case 'Q':
			case 'R':
			case 'S':
			case 'T':
			case 'U':
			case 'V':
			case 'W':
			case 'X':
			case 'Y':
			case 'Z':
			case '[':
			case '\\':
			case ']':
			case '^':
			case '_':
			case '`':
			case 'a':
			case 'b':
			case 'c':
			case 'd':
			case 'e':
			case 'f':
			case 'g':
			case 'h':
			case 'i':
			case 'j':
			case 'k':
			case 'l':
			case 'm':
			case 'n':
			case 'o':
			case 'p':
			case 'q':
			case 'r':
			case 's':
			case 't':
			case 'u':
			case 'v':
			case 'w':
			case 'x':
			case 'y':
			case 'z':
			case '{':
			case '|':
			case '}':
			case '~':
			case '\x7f':
			case '\x80':
			case '\x81':
			case '\x82':
			case '\x83':
			case '\x84':
			case '\x85':
			case '\x86':
			case '\x87':
			case '\x88':
			case '\x89':
			case '\x8a':
			case '\x8b':
			case '\x8c':
			case '\x8d':
			case '\x8e':
			case '\x8f':
			case '\x90':
			case '\x91':
			case '\x92':
			case '\x93':
			case '\x94':
			case '\x95':
			case '\x96':
			case '\x97':
			case '\x98':
			case '\x99':
			case '\x9a':
			case '\x9b':
			case '\x9c':
			case '\x9d':
			case '\x9e':
			case '\x9f':
			case '\xa0':
			case '\xa1':
			case '\xa2':
			case '\xa3':
			case '\xa4':
			case '\xa5':
			case '\xa6':
			case '\xa7':
			case '\xa8':
			case '\xa9':
			case '\xaa':
			case '\xab':
			case '\xac':
			case '\xad':
			case '\xae':
			case '\xaf':
			case '\xb0':
			case '\xb1':
			case '\xb2':
			case '\xb3':
			case '\xb4':
			case '\xb5':
			case '\xb6':
			case '\xb7':
			case '\xb8':
			case '\xb9':
			case '\xba':
			case '\xbb':
			case '\xbc':
			case '\xbd':
			case '\xbe':
			case '\xbf':
			case '\xc0':
			case '\xc1':
			case '\xc2':
			case '\xc3':
			case '\xc4':
			case '\xc5':
			case '\xc6':
			case '\xc7':
			case '\xc8':
			case '\xc9':
			case '\xca':
			case '\xcb':
			case '\xcc':
			case '\xcd':
			case '\xce':
			case '\xcf':
			case '\xd0':
			case '\xd1':
			case '\xd2':
			case '\xd3':
			case '\xd4':
			case '\xd5':
			case '\xd6':
			case '\xd7':
			case '\xd8':
			case '\xd9':
			case '\xda':
			case '\xdb':
			case '\xdc':
			case '\xdd':
			case '\xde':
			case '\xdf':
			case '\xe0':
			case '\xe1':
			case '\xe2':
			case '\xe3':
			case '\xe4':
			case '\xe5':
			case '\xe6':
			case '\xe7':
			case '\xe8':
			case '\xe9':
			case '\xea':
			case '\xeb':
			case '\xec':
			case '\xed':
			case '\xee':
			case '\xef':
			case '\xf0':
			case '\xf1':
			case '\xf2':
			case '\xf3':
			case '\xf4':
			case '\xf5':
			case '\xf6':
			case '\xf7':
			case '\xf8':
			case '\xf9':
			case '\xfa':
			case '\xfb':
			case '\xfc':
			case '\xfd':
			case '\xfe':
			case '\xff': state = S1; continue;
			default:  lx->lgetc = NULL; return TOK_UNKNOWN;
			}

		case S1: /* e.g. "a" */
			lx_literal_ungetc(lx, c); return TOK_CHAR;
		}
	}

	lx->lgetc = NULL;

	switch (state) {
	case S1: return TOK_CHAR;
	default: errno = EINVAL; return TOK_ERROR;
	}
}

const char *
lx_literal_name(enum lx_literal_token t)
{
	switch (t) {
	case TOK_CHAR: return "CHAR";
	case TOK_EOF:     return "EOF";
	case TOK_ERROR:   return "ERROR";
	case TOK_UNKNOWN: return "UNKNOWN";
	default: return "?";
	}
}

const char *
lx_literal_example(enum lx_literal_token (*z)(struct lx_literal_lx *), enum lx_literal_token t)
{
	assert(z != NULL);

	if (z == z0) {
		switch (t) {
		case TOK_CHAR: return "a";
		default: goto error;
		}
	}

error:

	errno = EINVAL;
	return NULL;
}

void
lx_literal_init(struct lx_literal_lx *lx)
{
	static const struct lx_literal_lx lx_default;

	assert(lx != NULL);

	*lx = lx_default;

	lx->c = EOF;
	lx->z = z0;

	lx->end.byte = 0;
	lx->end.line = 1;
	lx->end.col  = 1;
}

enum lx_literal_token
lx_literal_next(struct lx_literal_lx *lx)
{
	enum lx_literal_token t;

	assert(lx != NULL);
	assert(lx->z != NULL);

	if (lx->lgetc == NULL) {
		return TOK_EOF;
	}

	t = lx->z(lx);

	if (lx->push != NULL) {
		if (-1 == lx->push(lx, '\0')) {
			return TOK_ERROR;
		}
	}

	return t;
}

