---
name: Checkout
on: [ push, pull_request ]
jobs:
  build:
    name: "checkout"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Cache checkout
      uses: actions/cache@v3
      env:
        cache-name: cache-checkout
      with:
        path: .
        key: ${{ github.sha }}

